### ISSUE TITLE
RGB control on RGB+CCT bulb is not working. (tuya local)

### ISSUE THREAD

**Issue by klauswitt** [fhempy/fhempy#109]
Hi,

since version 528 local access to my RGB+CCT bulb is working now particially.
Colour changing with colour_data_v2 command is not working. Set command is existing but doesnt lead to an colour change.
State is still on "Initializing..." but the bulb can be switched by the "switch_led" command.

On tuya_cloud pendant of the bulb set name on/off can be used  for switching and colour_data_v2 is also working.

Device listing (ids changed):

Internals:
   CFGFN      
   DEF        tuya 4r27hrbrtno6k7q5 2sagtyg4ns8xxozdcukxhn 192.168.123.67 kbuxy3tw7874ya22 3.4 key secret
   DEVICEID   2sagtyg4ns8xxozdcukxhn
   FHEMPYTYPE tuya
   FUUID      639e4b34-f33f-d13c-162d-9d4d95c2509f7dc8
   IODev      fhempy_local
   NAME       tuya_local_2sagtyg4ns8xxozdcukxhn
   NR         570
   PYTHONTYPE tuya
   STATE      Initializing...
   TYPE       fhempy
   eventCount 39
   READINGS:
     2022-12-18 00:05:26   active_time     1670189824
     2022-12-18 00:05:26   biz_type        18
     2022-12-18 23:07:31   bright_value_v2 10.0
     2022-12-18 00:05:26   category        dj
     2022-12-18 00:05:26   countdown_1     0.0
     2022-12-18 00:05:26   create_time     1670189824
     2022-12-18 00:05:32   cycle_timing    AAAA
     2022-12-18 00:05:26   do_not_disturb  off
     2022-12-18 00:05:26   icon            smart/icon/ay1525830333575gYi61/d9a5f9bcc5fa2d6c047b8a56b2e691b0.png
     2022-12-18 00:05:26   id              2sagtyg4ns8xxozdcukxhn
     2022-12-18 00:05:26   ip              65.131.124.168
     2022-12-18 00:05:26   lat             50.1365
     2022-12-18 00:05:26   local_key       kbuxy3tw7874ya22
     2022-12-18 00:05:26   lon             8.6244
     2022-12-18 00:05:26   name            M-TCV1
     2022-12-18 23:06:08   online          1
     2022-12-18 00:05:26   owner_id        72805765
     2022-12-18 00:05:32   power_memory    AAEAAAAAAAABHgAA
     2022-12-18 00:05:26   product_id      4r27hrbrtno6k7q5
     2022-12-18 00:05:26   product_name    M-TCV1
     2022-12-18 00:05:32   random_timing   AAAA
     2022-12-18 00:05:31   rhythm_mode     AAAAAAA=
     2022-12-18 00:05:31   sleep_mode      AAA=
     2022-12-18 23:06:03   state           Initializing...
     2022-12-18 00:05:26   sub             0
     2022-12-18 23:07:39   switch_led      off
     2022-12-18 00:05:26   temp_value_v2   56.0
     2022-12-18 00:05:26   time_zone       +01:00
     2022-12-18 00:05:26   uid             eu1669756723579ISkWj
     2022-12-18 00:05:26   update_time     1671138004
     2022-12-18 00:05:26   uuid            8243228dfa810dd7
     2022-12-18 00:05:31   wakeup_mode     AAA=
     2022-12-18 23:07:23   work_mode       white
   args:
     tuya_local_2sagtyg4ns8xxozdcukxhn
     fhempy
     tuya
     4r27hrbrtno6k7q5
     2sagtyg4ns8xxozdcukxhn
     192.168.178.47
     kbuxy3tw7874ya22
     3.4
     key
     secret
   argsh:
Attributes:
   alias      M-TCV1
   dp_20      switch_led
   dp_209     cycle_timing
   dp_21      work_mode
   dp_210     random_timing
   dp_22      bright_value_v2
   dp_23      temp_value_v2
   dp_24      colour_data_v2
   dp_25      scene_data_v2
   dp_26      countdown_1
   dp_27      music_data
   dp_28      control_data
   dp_30      rhythm_mode
   dp_31      sleep_mode
   dp_32      wakeup_mode
   dp_33      power_memory
   dp_34      do_not_disturb
   group      tuya
   room       fhempy
   tuya_spec_functions [{'code': 'switch_led', 'dp_id': 20, 'type': 'Boolean', 'values': {}, 'desc': 'switch led'}, {'code': 'work_mode', 'dp_id': 21, 'type': 'Enum', 'values': {'range': ['white', 'colour', 'scene', 'music']}, 'desc': 'work mode'}, {'code': 'bright_value_v2', 'dp_id': 22, 'type': 'Integer', 'values': {'min': 10, 'max': 1000, 'scale': 0, 'step': 1}, 'desc': 'bright value v2'}, {'code': 'temp_value_v2', 'dp_id': 23, 'type': 'Integer', 'values': {'min': 0, 'max': 1000, 'scale': 0, 'step': 1}, 'desc': 'temp value v2'}, {'code': 'colour_data_v2', 'dp_id': 24, 'type': 'Json', 'values': {'h': {'min': 0, 'scale': 0, 'unit': '', 'max': 360, 'step': 1}, 's': {'min': 0, 'scale': 0, 'unit': '', 'max': 1000, 'step': 1}, 'v': {'min': 0, 'scale': 0, 'unit': '', 'max': 1000, 'step': 1}}, 'desc': 'colour data v2'}, {'code': 'scene_data_v2', 'dp_id': 25, 'type': 'Json', 'values': {'scene_num': {'min': 1, 'scale': 0, 'max': 8, 'step': 1}, 'scene_units': {'unit_change_mode': {'range': ['static', 'jump', 'gradient']}, 'unit_switch_duration': {'min': 0, 'scale': 0, 'max': 100, 'step': 1}, 'unit_gradient_duration': {'min': 0, 'scale': 0, 'max': 100, 'step': 1}, 'bright': {'min': 0, 'scale': 0, 'max': 1000, 'step': 1}, 'temperature': {'min': 0, 'scale': 0, 'max': 1000, 'step': 1}, 'h': {'min': 0, 'scale': 0, 'unit': '', 'max': 360, 'step': 1}, 's': {'min': 0, 'scale': 0, 'unit': '', 'max': 1000, 'step': 1}, 'v': {'min': 0, 'scale': 0, 'unit': '', 'max': 1000, 'step': 1}}}, 'desc': 'scene data v2'}, {'code': 'countdown_1', 'dp_id': 26, 'type': 'Integer', 'values': {'unit': 's', 'min': 0, 'max': 86400, 'scale': 0, 'step': 1}, 'desc': 'countdown 1'}, {'code': 'music_data', 'dp_id': 27, 'type': 'Json', 'values': {'change_mode': {'range': ['direct', 'gradient']}, 'bright': {'min': 0, 'scale': 0, 'unit': '', 'max': 1000, 'step': 1}, 'temperature': {'min': 0, 'scale': 0, 'unit': '', 'max': 1000, 'step': 1}, 'h': {'min': 0, 'scale': 0, 'unit': '', 'max': 360, 'step': 1}, 's': {'min': 0, 'scale': 0, 'unit': '', 'max': 255, 'step': 1}, 'v': {'min': 0, 'scale': 0, 'unit': '', 'max': 255, 'step': 1}}, 'desc': 'music data'}, {'code': 'control_data', 'dp_id': 28, 'type': 'Json', 'values': {'change_mode': {'range': ['direct', 'gradient']}, 'bright': {'min': 0, 'scale': 0, 'unit': '', 'max': 1000, 'step': 1}, 'temperature': {'min': 0, 'scale': 0, 'unit': '', 'max': 1000, 'step': 1}, 'h': {'min': 0, 'scale': 0, 'unit': '', 'max': 360, 'step': 1}, 's': {'min': 0, 'scale': 0, 'unit': '', 'max': 255, 'step': 1}, 'v': {'min': 0, 'scale': 0, 'unit': '', 'max': 255, 'step': 1}}, 'desc': 'control data'}, {'code': 'rhythm_mode', 'dp_id': 30, 'type': 'Raw', 'values': {'maxlen': 255}, 'desc': 'rhythm mode'}, {'code': 'sleep_mode', 'dp_id': 31, 'type': 'Raw', 'values': {'maxlen': 255}, 'desc': 'sleep mode'}, {'code': 'wakeup_mode', 'dp_id': 32, 'type': 'Raw', 'values': {'maxlen': 255}, 'desc': 'wakeup mode'}, {'code': 'power_memory', 'dp_id': 33, 'type': 'Raw', 'values': {}, 'desc': 'power memory'}, {'code': 'do_not_disturb', 'dp_id': 34, 'type': 'Boolean', 'values': {}, 'desc': 'do not disturb'}, {'code': 'cycle_timing', 'dp_id': 209, 'type': 'Raw', 'values': {}, 'desc': 'cycle timing'}, {'code': 'random_timing', 'dp_id': 210, 'type': 'Raw', 'values': {}, 'desc': 'random timing'}]
   tuya_spec_status [{'code': 'switch_led', 'dp_id': 20, 'type': 'Boolean', 'values': {}}, {'code': 'work_mode', 'dp_id': 21, 'type': 'Enum', 'values': {'range': ['white', 'colour', 'scene', 'music']}}, {'code': 'bright_value_v2', 'dp_id': 22, 'type': 'Integer', 'values': {'min': 10, 'max': 1000, 'scale': 0, 'step': 1}}, {'code': 'temp_value_v2', 'dp_id': 23, 'type': 'Integer', 'values': {'min': 0, 'max': 1000, 'scale': 0, 'step': 1}}, {'code': 'colour_data_v2', 'dp_id': 24, 'type': 'Json', 'values': {'h': {'min': 0, 'scale': 0, 'unit': '', 'max': 360, 'step': 1}, 's': {'min': 0, 'scale': 0, 'unit': '', 'max': 1000, 'step': 1}, 'v': {'min': 0, 'scale': 0, 'unit': '', 'max': 1000, 'step': 1}}}, {'code': 'scene_data_v2', 'dp_id': 25, 'type': 'Json', 'values': {'scene_num': {'min': 1, 'scale': 0, 'max': 8, 'step': 1}, 'scene_units': {'unit_change_mode': {'range': ['static', 'jump', 'gradient']}, 'unit_switch_duration': {'min': 0, 'scale': 0, 'max': 100, 'step': 1}, 'unit_gradient_duration': {'min': 0, 'scale': 0, 'max': 100, 'step': 1}, 'bright': {'min': 0, 'scale': 0, 'max': 1000, 'step': 1}, 'temperature': {'min': 0, 'scale': 0, 'max': 1000, 'step': 1}, 'h': {'min': 0, 'scale': 0, 'unit': '', 'max': 360, 'step': 1}, 's': {'min': 0, 'scale': 0, 'unit': '', 'max': 1000, 'step': 1}, 'v': {'min': 0, 'scale': 0, 'unit': '', 'max': 1000, 'step': 1}}}}, {'code': 'countdown_1', 'dp_id': 26, 'type': 'Integer', 'values': {'unit': 's', 'min': 0, 'max': 86400, 'scale': 0, 'step': 1}}, {'code': 'music_data', 'dp_id': 27, 'type': 'Json', 'values': {'change_mode': {'range': ['direct', 'gradient']}, 'bright': {'min': 0, 'scale': 0, 'unit': '', 'max': 1000, 'step': 1}, 'temperature': {'min': 0, 'scale': 0, 'unit': '', 'max': 1000, 'step': 1}, 'h': {'min': 0, 'scale': 0, 'unit': '', 'max': 360, 'step': 1}, 's': {'min': 0, 'scale': 0, 'unit': '', 'max': 255, 'step': 1}, 'v': {'min': 0, 'scale': 0, 'unit': '', 'max': 255, 'step': 1}}}, {'code': 'control_data', 'dp_id': 28, 'type': 'Json', 'values': {'change_mode': {'range': ['direct', 'gradient']}, 'bright': {'min': 0, 'scale': 0, 'unit': '', 'max': 1000, 'step': 1}, 'temperature': {'min': 0, 'scale': 0, 'unit': '', 'max': 1000, 'step': 1}, 'h': {'min': 0, 'scale': 0, 'unit': '', 'max': 360, 'step': 1}, 's': {'min': 0, 'scale': 0, 'unit': '', 'max': 255, 'step': 1}, 'v': {'min': 0, 'scale': 0, 'unit': '', 'max': 255, 'step': 1}}}, {'code': 'rhythm_mode', 'dp_id': 30, 'type': 'Raw', 'values': {'maxlen': '255'}}, {'code': 'sleep_mode', 'dp_id': 31, 'type': 'Raw', 'values': {'maxlen': '255'}}, {'code': 'wakeup_mode', 'dp_id': 32, 'type': 'Raw', 'values': {'maxlen': '255'}}, {'code': 'power_memory', 'dp_id': 33, 'type': 'Raw', 'values': {}}, {'code': 'do_not_disturb', 'dp_id': 34, 'type': 'Boolean', 'values': {}}, {'code': 'cycle_timing', 'dp_id': 209, 'type': 'Raw', 'values': {}}, {'code': 'random_timing', 'dp_id': 210, 'type': 'Raw', 'values': {}}]

**Comment by fhempy** [comment]
Bitte mit 0.1.536 testen. Poste bitte auch das fhempy Log wenn etwas nicht funktioniert. Danke!

**Comment by klauswitt** [comment]
Ich bin jetzt schon bei der 0.1.538

Da sich die Lampe gar nicht mehr ansteuern ließ, habe ich die tuya defines gelöscht und neu gemacht.
"defmod tuya_system fhempy tuya setup...."
Leider passiert bei einem "set tuya_system scan-devices" nichts.
Folgende Fehlermeldungen sind im Log zu finden:

2023-01-03 10:54:30,768 - INFO     - fhempy.lib.fhem_pythonbinding: Starting fhempy 0.1.538...
2023-01-03 10:54:30,773 - INFO     - fhempy.lib.fhem_pythonbinding: Waiting for FHEM connection
2023-01-03 10:54:30,808 - INFO     - websockets.server: server listening on 0.0.0.0:15733
2023-01-03 10:54:34,439 - INFO     - websockets.server: connection open
2023-01-03 10:54:34,441 - INFO     - fhempy.lib.fhem_pythonbinding: Incoming FHEM connection: 127.0.0.1
2023-01-03 10:54:34,563 - WARNING  - zeroconf: Error with socket 10 (('100.64.0.1', 5353))): [Errno 126] Required key not available
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 1056, in sendto
    self._sock.sendto(data, addr)
OSError: [Errno 126] Required key not available
2023-01-03 10:54:50,071 - WARNING  - asyncio: Executing <Task pending name='Task-30' coro=<fhempy.onMessage() running at /opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/fhem_pythonbinding.py:175> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f77a81ee0>()] created at /usr/lib/python3.9/asyncio/base_events.py:424> created at /usr/lib/python3.9/asyncio/tasks.py:361> took 0.308 seconds
2023-01-03 10:55:07,111 - ERROR    - tuya_system: Exception raised by task: <Task finished name='Task-78' coro=<FhemModule._run_coro() done, defined at /opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/generic.py:194> exception=TypeError('can only concatenate str (not "dict") to str') created at /usr/lib/python3.9/asyncio/tasks.py:361>
Traceback (most recent call last):
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/generic.py", line 202, in _handle_task_result
    task.result()
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/generic.py", line 196, in _run_coro
    await coro
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/tuya/tuya.py", line 671, in _scan_devices
    json_data = await utils.run_blocking(
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/utils.py", line 72, in run_blocking
    return await asyncio.get_event_loop().run_in_executor(pool, function)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/fhem/.local/lib/python3.9/site-packages/tinytuya/Cloud.py", line 244, in getdevices
    uid = self._getuid(self.apiDeviceID)
  File "/opt/fhem/.local/lib/python3.9/site-packages/tinytuya/Cloud.py", line 220, in _getuid
    response_dict = self._tuyaplatform(uri)
  File "/opt/fhem/.local/lib/python3.9/site-packages/tinytuya/Cloud.py", line 134, in _tuyaplatform
    payload = self.apiKey + self.token + str(now)
TypeError: can only concatenate str (not "dict") to str
2023-01-03 10:55:44,568 - ERROR    - tuya_system: Exception raised by task: <Task finished name='Task-99' coro=<FhemModule._run_coro() done, defined at /opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/generic.py:194> exception=TypeError('can only concatenate str (not "dict") to str') created at /usr/lib/python3.9/asyncio/tasks.py:361>
Traceback (most recent call last):
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/generic.py", line 202, in _handle_task_result
    task.result()
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/generic.py", line 196, in _run_coro
    await coro
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/tuya/tuya.py", line 671, in _scan_devices
    json_data = await utils.run_blocking(
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/utils.py", line 72, in run_blocking
    return await asyncio.get_event_loop().run_in_executor(pool, function)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/fhem/.local/lib/python3.9/site-packages/tinytuya/Cloud.py", line 244, in getdevices
    uid = self._getuid(self.apiDeviceID)
  File "/opt/fhem/.local/lib/python3.9/site-packages/tinytuya/Cloud.py", line 220, in _getuid
    response_dict = self._tuyaplatform(uri)
  File "/opt/fhem/.local/lib/python3.9/site-packages/tinytuya/Cloud.py", line 134, in _tuyaplatform
    payload = self.apiKey + self.token + str(now)
TypeError: can only concatenate str (not "dict") to str

**Comment by fhempy** [comment]
Wie sieht dein define dazu aus? Kann es sein, dass API_KEY oder API_SECRET fehlen oder falsch hinterlegt sind?

**Comment by klauswitt** [comment]
Hier ist das define.
Ich hatte die define Zeile zwischen den updates nicht verändert (wenn ich das Device gelöscht habe, dann habe ich das define vorher kopiert und nach dem löschen direkt wieder angelegt)
API_KEY, API_SECRET und DEVICE_ID habe ich nochmals überprüft, die sind korrekt.

Internals:
   API_KEY    j...g
   API_SECRET 8...c
   DEF        tuya setup j...g 8...c b...x
   DEVICEID   0
   FHEMPYTYPE tuya
   FUUID      63b3fb69-f33f-d13c-9dcb-223bf8409d5f66cd
   FVERSION   10_fhempy.pm:0.182830/2019-01-16
   IODev      [fhempy_local](https://f16.ddnss.de/fhem?detail=fhempy_local)
   NAME       [tuya_system](https://f16.ddnss.de/fhem?detail=tuya_system)
   NR         58
   PYTHONTYPE tuya
   REGION     eu
   STATE      ready
   TYPE       fhempy
   eventCount 5
   READINGS:
     2023-01-04 22:01:11   state           ready
   args:
     [tuya_system](https://f16.ddnss.de/fhem?detail=tuya_system)
     fhempy
     tuya
     setup
     j...g
     8...c
     b...x
   argsh:
Attributes:
   group      tuya
   room       fhempy

**Comment by fhempy** [comment]
Ich weiß nicht ob das jetzt durch das Kopieren entstanden ist, oder ob du wirklich Links im Define drin hast:
```
args:
     [tuya_system](https://f16.ddnss.de/fhem?detail=tuya_system)
```
Vielleicht nochmals manuell das Device anlegen ohne copy&paste.

**Comment by klauswitt** [comment]
Das passt schon. IODev und NAME  werden bei einem list Befehl im Browser als Link dargestellt. 
Das ist beim Kopieren des list Ergebnisses mit hierher übertragen worden. 
Letztendlich habe ich nach dem löschen des Devices auch nur:
tuya setup j...g 8...c b...x ausgeführt. 

Weißt das Log auf einen Fehler im define hin?

**Comment by fhempy** [comment]
Ah, sorry, jetzt bin ich durcheinander gekommen.

tuya legt die Devices NICHT automatisch an. Da muss man vorher ein scan_devices machen und dann mit create_device anlegen.

Der Fehler zeigt folgendes
```
payload = self.apiKey + self.token + str(now)
TypeError: can only concatenate str (not "dict") to str
```
Ich dachte apiKey ist vielleicht falsch, aber wahrscheinlich ist es self.token. Prüfe bitte sicherheitshalber nochmals API KEY und SECRET.

**Comment by klauswitt** [comment]
KEY und SECRET stimmen definitiv. Ich habe die identischen Daten auch bei tuya_cloud drinnen und der connected sich. Wenn ich dort nur ein Zeichen von KEY oder SECRET ändere kommt ein login Fehler.
Auch die DEVICE_ID habe ich doppelt überprüft.

**Comment by fhempy** [comment]
Teste bitte folgendes
```bash
sudo -u fhem bash
python3
```

dann in Python3 folgendes eingeben
```python
import tinytuya
tinytuya.Cloud("eu", "KEY", "SECRET", "DEVICEID")
self.token
```

Du solltest dann eine Fehlermeldung im JSON Format sehen.

**Comment by klauswitt** [comment]
Es kommt kein Fehler sondern ein String:
'3c2eafb6ca47a8d233881908a896ca2f'

**Comment by fhempy** [comment]
Mach dann noch ein
```python
tt.getdevices()
```
und schau ob du die Liste der Devices erhältst

**Comment by fhempy** [comment]
Ist in deinem API KEY / SECRET oder DEVICEID irgendwo ein = drin oder irgendein Sonderzeichen?

**Comment by klauswitt** [comment]
> Ist in deinem API KEY / SECRET oder DEVICEID irgendwo ein = drin oder irgendein Sonderzeichen?

nein, nur Zahlen und Buchstaben



> Mach dann noch ein
> 
> ```python
> tt.getdevices()
> ```
> 
> und schau ob du die Liste der Devices erhältst

hier hängt es scheinbar, jetzt kommt ein Fehler:

{'Error': 'Error Response from Tuya Cloud', 'Err': '913', 'Payload': "Error from Tuya Cloud: Code 28841002: 'No permissions. Your subscription to cloud development plan has expired.'"}

Die Frage ist jetzt wo da was abgelaufen ist

**Comment by fhempy** [comment]
Sehr gut, jetzt haben wir den Fehler.

Das musst du auf der Tuya IoT Plattform schauen:
 - iot.tuya.com
 - Dann links Cloud und dort dann Cloud Services auswählen
 - jetzt solltest du die Liste an Services sehen und dort ist sicher eines mit expired gekennzeichnet

**Comment by klauswitt** [comment]
Der IoT Core ist "In Service". Der war nur einen Monat verfügbar. Ich habe jetzt die Verlängerung der Trial um 6 Monate beantragt. Mal schauen ob das klappt.
Du scheinst dieses Problem nicht zu haben. Habe ich bei der Projekterstellung was übersehen oder muss das jetzt regelmäßig erneuert werden?

Wäre es möglich, den die Fehlermeldungen der Cloud ans FHEM Modul durchzureichen?
Das würde Dir sicher auch viele nervige Fragen ersparen. ;)

**Comment by fhempy** [comment]
Hab ich schon integriert, dass es zumindest als ERROR im Log angezeigt wird :)

**Comment by klauswitt** [comment]
> Hab ich schon integriert, dass es zumindest als ERROR im Log angezeigt wird :)
perfekt

die Testperiode des IoT Core wurde Seitens Tuya auf 6 Monate verlängert. Allerdings weiß ich immer noch nicht wie das danach weitergeht. Die Preisgestaltung richtet sich eher an Unternehmen.
Hast du keine zeitliche Beschränkung bei den Cloud Services?

Folgendes habe ich mit 0.1.543 getestet

Jetzt funktioniert auch scan_devices wieder und die beiden Lampen wurden gefunden und konnten agelegt werden.
on/off gibt es nicht als direktes set. Das geht nur über "set name switch_led on|off". Das lässt sich problemlos mit eventMap lösen. Aber soll das so sein? Wenn die selben lampen über tuya_cloud angebunden werden ist on/off direkt vorhanden.

Nach dem Anlegen war state kurz "Initializing..." danach "Ready". Allerdings steht seit dem ersten FHEM Neustart danach jetzt nur noch "Initializing..." im state. 

Diese sets funktionieren:
bright_value_v2, switch_led, temp_value_v2, work_mode

Was weiterhin nicht funktioniert ist:
colour_data_v2 wird als reading zwar korrekt aktualisiert, kann aber nicht gesetzt werden.
Im log erscheint nichts wenn ich z.B. "set name colour_data_v2 FF0000" ausführe.

Im log erscheinen minütlich folgende Einträge (einer pro Lampe):

2023-01-07 23:53:03,227 - ERROR    - tuya_local_b...x: Failed to update readings
Traceback (most recent call last):
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/tuya/tuya.py", line 633, in update_readings
    flat_json = self.convert_json(status[dp], st)
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/tuya/tuya.py", line 580, in convert_json
    if "category" in self.info_dict and self.info_dict["category"] == "zndb":
AttributeError: 'tuya' object has no attribute 'info_dict'
2023-01-07 23:53:03,244 - ERROR    - tuya_local_b...d: Failed to update readings
Traceback (most recent call last):
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/tuya/tuya.py", line 633, in update_readings
    flat_json = self.convert_json(status[dp], st)
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/tuya/tuya.py", line 580, in convert_json
    if "category" in self.info_dict and self.info_dict["category"] == "zndb":
AttributeError: 'tuya' object has no attribute 'info_dict'

**Comment by fhempy** [comment]
Bitte mit 0.1.544 testen, dort ist der Fehler behoben und colour_v2 tut damit auch.
Teste dann bitte auch ob Initializing... wirklich stehen bleibt, sollte immer auf ready gehen.

Cloud liefert on/off zurück, bei local kommt switch_led. Ich muss das noch prüfen was ich da machen kann, da mein Code komplett generisch ist.
Devices können z.B. auch
switch
switch_led
switch_1
...
haben, was dann on/off ist kann man daher nicht immer so einfach sagen.

**Comment by klauswitt** [comment]
Mit der 0.1.546 kommen die Fehler im Log nicht mehr.
colour_data_v2 funktioniert jetzt auch
Das reading switch_led gibt es nicht mehr und wird direkt zu on/off gemappt
state geht nach dem Neustart von Initializing... auf den jeweiligen Schaltzustand.

Saubere Arbeit :)

Eine inkonsistenz ist mir aufgefallen.
Wenn bei den Lampen work_mode auf white gestellt ist, dann ändert colour_data_v2 nichts am Zustand der Lampe.
Sobald ich den work_mode auf colour stelle, wird die geänderte Farbe sofort eingestellt.

Wenn ich allerdings den work_mode auf colour gestellt habe und dann bright_value_v2 oder temp_value_v2 verstelle, dann stellt sich der work mode der Lampe automatisch von colour auf white.

**Comment by fhempy** [comment]
Das ist korrekt, work_mode muss auf colour umgestellt werden damit die Farbe dargestellt wird. Ich überlege mir da mal was wie man das lösen kann.

**Comment by fhempy** [comment]
Bitte 0.1.547 testen

**Comment by klauswitt** [comment]
> Bitte 0.1.547 testen

Perfekt. Funktioniert!
Wenn colour_data_v2 gesetzt wird, dann wird jetzt auch direkt auf work_mode colour gesetzt.

Es gibt noch ein paar Warnings im Log, die kommen aber unabhängig von set Aktionen:

2023-01-08 19:41:49,643 - WARNING  - asyncio: Executing <Task pending name='Task-45207' coro=<FhemModule._run_coro() running at /opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/generic.py:196> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f971a24f0>()] created at /usr/lib/python3.9/asyncio/base_events.py:424> cb=[FhemModule._handle_task_result()] created at /usr/lib/python3.9/asyncio/tasks.py:361> took 0.129 seconds
2023-01-08 19:45:00,506 - WARNING  - asyncio: Executing <Task pending name='Task-128' coro=<main() running at /opt/fhem/.local/lib/python3.9/site-packages/tinytuya/__init__.py:247> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f95835220>()] created at /usr/lib/python3.9/asyncio/base_events.py:424> created at /usr/lib/python3.9/asyncio/tasks.py:361> took 0.154 seconds
2023-01-08 19:48:28,599 - WARNING  - asyncio: Executing <Task pending name='Task-5' coro=<WebSocketCommonProtocol.transfer_data() running at /opt/fhem/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py:945> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f9464dd00>()] created at /usr/lib/python3.9/asyncio/base_events.py:424> cb=[<TaskWakeupMethWrapper object at 0x7f97263cd0>(), _wait.<locals>._on_completion() at /usr/lib/python3.9/asyncio/tasks.py:513] created at /opt/fhem/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py:344> took 0.172 seconds
2023-01-08 19:52:26,552 - WARNING  - asyncio: Executing <Task pending name='Task-5' coro=<WebSocketCommonProtocol.transfer_data() running at /opt/fhem/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py:945> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f960743d0>()] created at /usr/lib/python3.9/asyncio/base_events.py:424> cb=[<TaskWakeupMethWrapper object at 0x7f97263cd0>(), _wait.<locals>._on_completion() at /usr/lib/python3.9/asyncio/tasks.py:513] created at /opt/fhem/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py:344> took 0.201 seconds
2023-01-08 19:57:16,725 - WARNING  - asyncio: Executing <Task pending name='Task-5' coro=<WebSocketCommonProtocol.transfer_data() running at /opt/fhem/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py:945> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f972f4880>()] created at /usr/lib/python3.9/asyncio/base_events.py:424> cb=[<TaskWakeupMethWrapper object at 0x7f97263cd0>(), _wait.<locals>._on_completion() at /usr/lib/python3.9/asyncio/tasks.py:513] created at /opt/fhem/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py:344> took 0.236 seconds
2023-01-08 20:02:51,167 - WARNING  - asyncio: Executing <Task pending name='Task-113' coro=<main() running at /opt/fhem/.local/lib/python3.9/site-packages/tinytuya/__init__.py:247> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f96074fa0>()] created at /usr/lib/python3.9/asyncio/base_events.py:424> created at /usr/lib/python3.9/asyncio/tasks.py:361> took 0.274 seconds
2023-01-08 20:09:14,555 - WARNING  - asyncio: Executing <Task pending name='Task-181020' coro=<FhemModule._run_coro() running at /opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/generic.py:196> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f9444cb50>()] created at /usr/lib/python3.9/asyncio/base_events.py:424> cb=[FhemModule._handle_task_result()] created at /usr/lib/python3.9/asyncio/tasks.py:361> took 0.321 seconds
2023-01-08 20:16:25,479 - WARNING  - asyncio: Executing <Task pending name='Task-5' coro=<WebSocketCommonProtocol.transfer_data() running at /opt/fhem/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py:945> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f971284f0>()] created at /usr/lib/python3.9/asyncio/base_events.py:424> cb=[<TaskWakeupMethWrapper object at 0x7f97263cd0>(), _wait.<locals>._on_completion() at /usr/lib/python3.9/asyncio/tasks.py:513] created at /opt/fhem/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py:344> took 0.366 seconds
2023-01-08 20:24:41,548 - WARNING  - asyncio: Executing <Task pending name='Task-257484' coro=<FhemModule._run_coro() running at /opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/generic.py:196> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f97213820>()] created at /usr/lib/python3.9/asyncio/base_events.py:424> cb=[FhemModule._handle_task_result()] created at /usr/lib/python3.9/asyncio/tasks.py:361> took 0.426 seconds
2023-01-08 20:34:07,249 - WARNING  - asyncio: Executing <Task finished name='Task-304124' coro=<Lock.acquire() done, defined at /usr/lib/python3.9/asyncio/locks.py:99> result=True created at /usr/lib/python3.9/asyncio/tasks.py:462> took 0.493 seconds

**Comment by fhempy** [comment]
Die Warnings sind normal. Ich habe asyncio noch im Debug Mode laufen und da kommt immer so ein Warning wenn etwas mehr als 100ms blockt. Ich werde das in nächster Zeit deaktivieren.

Danke für das Testen, Issue schließe ich nachdem nun alles läuft.
