### ISSUE TITLE
Version 0.1.543: Error "missing 1 required positional argument: 'skill_number'"

### ISSUE THREAD

**Issue by SiggiBS** [fhempy/fhempy#116]
With the new modul version 0.1.543 my Meross Switch mss710 can't switched on or off anymore. 

I have two meross devices running in my meross app. A Smart Essential Oil Defuser (mod150) and a Meross Switch mss710. After deleting and reinstall the meross-integration now there are no meross-devices listed.

Logfile-Entries:

2023-01-07 13:18:32,654 - INFO     - fhempy.lib.fhem_pythonbinding: Start update...
2023-01-07 13:18:32,656 - INFO     - fhempy.lib.pkg_installer: Attempting install of fhempy
2023-01-07 13:18:39,517 - INFO     - fhempy.lib.pkg_installer: Successfully installed fhempy update!
2023-01-07 13:18:39,534 - INFO     - fhempy.lib.fhem_pythonbinding: Restart initiated...
2023-01-07 13:18:39,537 - INFO     - fhempy.lib.fhem_pythonbinding: All modules successfully undefined!
2023-01-07 13:18:39,539 - INFO     - websockets.server: server closing
2023-01-07 13:18:49,557 - INFO     - websockets.server: connection closed
2023-01-07 13:18:49,558 - INFO     - websockets.server: server closed
2023-01-07 13:18:49,559 - INFO     - fhempy.lib.fhem_pythonbinding: Exit 1
2023-01-07 13:18:50,895 - INFO     - fhempy.lib.fhem_pythonbinding: Starting fhempy 0.1.543...
2023-01-07 13:18:50,903 - INFO     - fhempy.lib.fhem_pythonbinding: Waiting for FHEM connection
2023-01-07 13:18:50,938 - INFO     - websockets.server: server listening on 0.0.0.0:15733
2023-01-07 13:18:59,762 - INFO     - websockets.server: connection open
2023-01-07 13:18:59,768 - INFO     - fhempy.lib.fhem_pythonbinding: Incoming FHEM connection: 127.0.0.1
2023-01-07 13:19:00,974 - ERROR    - meross_integration: Exception raised by task: <Task finished coro=<FhemModule._run_coro() done, defined at /opt/fhem/.local/lib/python3.7/site-packages/fhempy/lib/generic.py:194> exception=TypeError("__init__() missing 1 required positional argument: 'skill_number'") created at /usr/lib/python3.7/asyncio/tasks.py:325>
Traceback (most recent call last):
  File "/opt/fhem/.local/lib/python3.7/site-packages/fhempy/lib/generic.py", line 202, in _handle_task_result
    task.result()
  File "/opt/fhem/.local/lib/python3.7/site-packages/fhempy/lib/generic.py", line 196, in _run_coro
    await coro
  File "/opt/fhem/.local/lib/python3.7/site-packages/fhempy/lib/meross/meross_setup.py", line 37, in run_setup
    await manager.async_device_discovery()
  File "/opt/fhem/.local/lib/python3.7/site-packages/meross_iot/manager.py", line 331, in async_device_discovery
    http_devices = await self._http_client.async_list_devices()
  File "/opt/fhem/.local/lib/python3.7/site-packages/meross_iot/http_api.py", line 417, in async_list_devices
    return [HttpDeviceInfo.from_dict(x) for x in result]
  File "/opt/fhem/.local/lib/python3.7/site-packages/meross_iot/http_api.py", line 417, in <listcomp>
    return [HttpDeviceInfo.from_dict(x) for x in result]
  File "/opt/fhem/.local/lib/python3.7/site-packages/meross_iot/model/shared.py", line 27, in from_dict
    obj = cls(**new_dict)
TypeError: __init__() missing 1 required positional argument: 'skill_number'

**Comment by fhempy** [comment]
Thanks for reporting!

Meross did a breaking change on their APIs:
https://github.com/albertogeniola/MerossIot#-breaking-changes-from-meross-api-

I updated the library to the latest version. The fix is available in version 0.1.544 or higher.

**Comment by SiggiBS** [comment]
Great. Many thanks for the quick update and your work on the system. Everything works fine now.
