### ISSUE TITLE
[fhempy Tuya local] über Alexa und Homebridgemapping lässt sich die Farbe colour_data_v2 nicht ändern

### ISSUE THREAD

**Issue by Barneybaer84** [fhempy/fhempy#119]
Alexa schickt nummerische Zeichen, wenn über Sprache oder App die Farbe geändert wird. Im lokalen Device wird nur Hex verstanden. 
Z.B. wenn ich in der Alexa App auf Grün stelle, schickt die App dies: "executing set cmd for Hue with value 120"
Mit "set tuya_local_xxxxx colour_data_v2 120" zb. kommt ein Fehler. 
`Failed to execute function Set: Traceback (most recent call last):
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/fhem_pythonbinding.py", line 367, in handle_function
    ret = await self.execute_function(hash, fhem_reply_done, nmInstance)
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/fhem_pythonbinding.py", line 438, in execute_function
    ret = await asyncio.wait_for(
  File "/usr/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/generic.py", line 186, in Set
    return await utils.handle_set(self._conf_set, self, hash, args, argsh)
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/utils.py", line 326, in handle_set
    return await fct_call(hash, final_params)
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/tuya/tuya.py", line 321, in set_colour_data_v2
    rgb = self.fhemrgb2rgb(params["new_val"])
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/tuya/tuya.py", line 337, in fhemrgb2rgb
    blue = int(rgb[4:6], base=16)
ValueError: invalid literal for int() with base 16: ''`

**Comment by Barneybaer84** [comment]
Hat sich erledigt. Ich habe statt Hue RGB benutzt.
