### ISSUE TITLE
[Request] fhempy peer support for Ubuntu

### ISSUE THREAD

**Issue by JorinL** [fhempy/fhempy#126]
Currently the fhempy peer does not work on Ubuntu, some libraries used do not support Ubuntu - as far as I understood the log correctly.

Intel NUC as Smarthome Server has also BLE and could be a nice upgrade to an Raspi ZeroW.

**Comment by fhempy** [comment]
Can you please provide logs? Without logs it's hard to say anything ;)

**Comment by JorinL** [comment]
Will do.

Eventually need to reinstall it again.
Or the logs are still there - where does fhempy stores its logs?

**Comment by fhempy** [comment]
fhempy log is written to syslog

**Comment by JorinL** [comment]
This passage was it where I got the idea from, that it is not compatible :-)

```
Feb  2 15:00:39 homeland systemd[1]: Started fhempy.
Feb  2 15:00:40 homeland fhempy[3331003]: 2023-02-02 15:00:40,233 - INFO     - fhempy.lib.fhem_pythonbinding: Starting fhempy 0.1.587...
Feb  2 15:00:40 homeland fhempy[3331003]: 2023-02-02 15:00:40,234 - INFO     - fhempy.lib.fhem_pythonbinding: Advertise fhempy on local network with 192.168.0.7:15733
Feb  2 15:00:40 homeland fhempy[3331003]: 2023-02-02 15:00:40,589 - INFO     - fhempy.lib.fhem_pythonbinding: Waiting for FHEM connection
Feb  2 15:00:40 homeland fhempy[3331003]: 2023-02-02 15:00:40,604 - INFO     - websockets.server: server listening on 0.0.0.0:15733
Feb  2 15:01:52 homeland fhempy[3331003]: 2023-02-02 15:01:52,053 - INFO     - websockets.server: connection open
Feb  2 15:01:52 homeland fhempy[3331003]: 2023-02-02 15:01:52,054 - INFO     - fhempy.lib.fhem_pythonbinding: Incoming FHEM connection: 172.17.0.9
Feb  2 15:01:52 homeland fhempy[3331003]: 2023-02-02 15:01:52,059 - INFO     - websockets.server: connection open
Feb  2 15:01:52 homeland fhempy[3331003]: 2023-02-02 15:01:52,059 - INFO     - fhempy.lib.fhem_pythonbinding: Incoming FHEM connection: 172.17.0.9
Feb  2 15:01:52 homeland fhempy[3331003]: /usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
Feb  2 15:01:52 homeland fhempy[3331003]:   warnings.warn(
Feb  2 15:01:52 homeland fhempy[3331003]: /usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release
Feb  2 15:01:52 homeland fhempy[3331003]:   warnings.warn(
Feb  2 15:01:52 homeland fhempy[3331003]: 2023-02-02 15:01:52,132 - INFO     - websockets.server: connection open
Feb  2 15:01:52 homeland fhempy[3331003]: 2023-02-02 15:01:52,133 - INFO     - fhempy.lib.fhem_pythonbinding: Incoming FHEM connection: 172.17.0.9
Feb  2 15:01:52 homeland fhempy[3331003]: 2023-02-02 15:01:52,140 - INFO     - websockets.server: connection open
Feb  2 15:01:52 homeland fhempy[3331003]: 2023-02-02 15:01:52,140 - INFO     - fhempy.lib.fhem_pythonbinding: Incoming FHEM connection: 172.17.0.9
Feb  2 15:01:52 homeland fhempy[3331003]: 2023-02-02 15:01:52,150 - ERROR    - fhempy.lib.fhem_pythonbinding: Connection closed error
Feb  2 15:01:52 homeland fhempy[3331003]: Traceback (most recent call last):
Feb  2 15:01:52 homeland fhempy[3331003]:   File "/home/jorin/.local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 945, in transfer_data
Feb  2 15:01:52 homeland fhempy[3331003]:     message = await self.read_message()
Feb  2 15:01:52 homeland fhempy[3331003]:   File "/home/jorin/.local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1015, in read_message
Feb  2 15:01:52 homeland fhempy[3331003]:     frame = await self.read_data_frame(max_size=self.max_size)
Feb  2 15:01:52 homeland fhempy[3331003]:   File "/home/jorin/.local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1090, in read_data_frame
Feb  2 15:01:52 homeland fhempy[3331003]:     frame = await self.read_frame(max_size)
Feb  2 15:01:52 homeland fhempy[3331003]:   File "/home/jorin/.local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1145, in read_frame
Feb  2 15:01:52 homeland fhempy[3331003]:     frame = await Frame.read(
Feb  2 15:01:52 homeland fhempy[3331003]:   File "/home/jorin/.local/lib/python3.10/site-packages/websockets/legacy/framing.py", line 70, in read
Feb  2 15:01:52 homeland fhempy[3331003]:     data = await reader(2)
Feb  2 15:01:52 homeland fhempy[3331003]:   File "/usr/lib/python3.10/asyncio/streams.py", line 706, in readexactly
Feb  2 15:01:52 homeland fhempy[3331003]:     raise exceptions.IncompleteReadError(incomplete, n)
Feb  2 15:01:52 homeland fhempy[3331003]: asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes
Feb  2 15:01:52 homeland fhempy[3331003]: The above exception was the direct cause of the following exception:
Feb  2 15:01:52 homeland fhempy[3331003]: Traceback (most recent call last):
Feb  2 15:01:52 homeland fhempy[3331003]:   File "/home/jorin/.local/lib/python3.10/site-packages/fhempy/lib/fhem_pythonbinding.py", line 80, in pybinding
Feb  2 15:01:52 homeland fhempy[3331003]:     async for message in websocket:
Feb  2 15:01:52 homeland fhempy[3331003]:   File "/home/jorin/.local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 482, in __aiter__
Feb  2 15:01:52 homeland fhempy[3331003]:     yield await self.recv()
Feb  2 15:01:52 homeland fhempy[3331003]:   File "/home/jorin/.local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 553, in recv
Feb  2 15:01:52 homeland fhempy[3331003]:     await self.ensure_open()
Feb  2 15:01:52 homeland fhempy[3331003]:   File "/home/jorin/.local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 921, in ensure_open
Feb  2 15:01:52 homeland fhempy[3331003]:     raise self.connection_closed_exc()
Feb  2 15:01:52 homeland fhempy[3331003]: websockets.exceptions.ConnectionClosedError: no close frame received or sent
Feb  2 15:01:52 homeland fhempy[3331003]: 2023-02-02 15:01:52,158 - INFO     - fhempy.lib.fhem_pythonbinding: Restart fhempy
Feb  2 15:01:52 homeland fhempy[3331003]: 2023-02-02 15:01:52,162 - INFO     - websockets.server: server closing
Feb  2 15:01:52 homeland fhempy[3331003]: 2023-02-02 15:01:52,165 - INFO     - websockets.server: connection closed

```

**Comment by fhempy** [comment]
Could it be that you defined multiple BindingsIo devices in Fhem? The log shows that multiple connections are setup from one fhem instance.

**Comment by JorinL** [comment]
Mh it should have been only one.

**Comment by fhempy** [comment]
Yes, please. I think others are already running fhempy on Ubuntu successfully.

**Comment by fhempy** [comment]
Please open the issue again if the error still occurs. I read already from others that they are running fhempy on Ubuntu, therefore I assume it should work.

**Comment by JorinL** [comment]
Just to return to this -> Works as expected :-)
