### ISSUE TITLE
Wiener Netze Smartmeter update 

### ISSUE THREAD

**Issue by schami23** [fhempy/fhempy#136]
Unfortunately, the module does not update itself automatically. can you add an update function to update the data manually?

**Comment by fhempy** [comment]
Thanks for reporting! Can you please check with the latest version and see the fhempy log if exceptions occur?

**Comment by fhempy** [comment]
Thanks!

Can you check if it still works even when the error is printed? Furthermore, please test with the latest version and post the output of the fhempy log. I added the stacktrace to the log to identify the root cause.

**Comment by schami23** [comment]
here is the output from the log file

```
Mar 24 18:04:32 xxxxxxxxxx fhempy[13559]: 2023-03-24 18:04:32,719 - ERROR    - fhempy.lib.wienernetze_smartmeter.api.client: Something really wrong happened! - list index out of range
Mar 24 18:04:32 xxxxxxxxxx fhempy[13559]: Traceback (most recent call last):
Mar 24 18:04:32 xxxxxxxxxx fhempy[13559]:   File "/home/xxxxxxxxx/.local/lib/python3.9/site-packages/fhempy/lib/wienernetze_smartmeter/api/client.py", line 213, in _request
Mar 24 18:04:32 xxxxxxxxxx fhempy[13559]:     await self.refresh_token()
Mar 24 18:04:32 xxxxxxxxxx fhempy[13559]:   File "/home/xxxxxxxxx/.local/lib/python3.9/site-packages/fhempy/lib/wienernetze_smartmeter/api/client.py", line 84, in refresh_token
Mar 24 18:04:32 xxxxxxxxxx fhempy[13559]:     data=const.build_access_token_args(code=await self._get_auth_code()),
Mar 24 18:04:32 xxxxxxxxxx fhempy[13559]:   File "/home/xxxxxxxxx/.local/lib/python3.9/site-packages/fhempy/lib/wienernetze_smartmeter/api/client.py", line 48, in _get_auth_code
Mar 24 18:04:32 xxxxxxxxxx fhempy[13559]:     action = await self._get_login_action()
Mar 24 18:04:32 xxxxxxxxxx fhempy[13559]:   File "/home/xxxxxxxxx/.local/lib/python3.9/site-packages/fhempy/lib/wienernetze_smartmeter/api/client.py", line 44, in _get_login_action
Mar 24 18:04:32 xxxxxxxxxx fhempy[13559]:     return tree.xpath("(//form/@action)")[0]
Mar 24 18:04:32 xxxxxxxxxx fhempy[13559]: IndexError: list index out of range
Mar 24 18:04:32 xxxxxxxxxx fhempy[13559]: 2023-03-24 18:04:32,804 - ERROR    - fhempy.lib.wienernetze_smartmeter.api.client: Something really wrong happened! - list index out of range
Mar 24 18:04:32 xxxxxxxxxx fhempy[13559]: Traceback (most recent call last):
Mar 24 18:04:32 xxxxxxxxxx fhempy[13559]:   File "/home/xxxxxxxxx/.local/lib/python3.9/site-packages/fhempy/lib/wienernetze_smartmeter/api/client.py", line 213, in _request
Mar 24 18:04:32 xxxxxxxxxx fhempy[13559]:     await self.refresh_token()
Mar 24 18:04:32 xxxxxxxxxx fhempy[13559]:   File "/home/xxxxxxxxx/.local/lib/python3.9/site-packages/fhempy/lib/wienernetze_smartmeter/api/client.py", line 84, in refresh_token
Mar 24 18:04:32 xxxxxxxxxx fhempy[13559]:     data=const.build_access_token_args(code=await self._get_auth_code()),
Mar 24 18:04:32 xxxxxxxxxx fhempy[13559]:   File "/home/xxxxxxxxx/.local/lib/python3.9/site-packages/fhempy/lib/wienernetze_smartmeter/api/client.py", line 48, in _get_auth_code
Mar 24 18:04:32 xxxxxxxxxx fhempy[13559]:     action = await self._get_login_action()
Mar 24 18:04:32 xxxxxxxxxx fhempy[13559]:   File "/home/xxxxxxxxx/.local/lib/python3.9/site-packages/fhempy/lib/wienernetze_smartmeter/api/client.py", line 44, in _get_login_action
Mar 24 18:04:32 xxxxxxxxxx fhempy[13559]:     return tree.xpath("(//form/@action)")[0]
Mar 24 18:04:32 xxxxxxxxxx fhempy[13559]: IndexError: list index out of range
```

**Comment by fhempy** [comment]
Does it stop updating the readings as soon as this error occurs?

**Comment by schami23** [comment]
it updates the readings only when fhem is restarted or fhempy updated.
it comes every hour this error message.

**Comment by fhempy** [comment]
I changed the behavior and I clear all cookies now on each new request. I think that should help. Please let me know if it works for you. Thanks!

**Comment by schami23** [comment]
yes now it works

Thanks
