### ISSUE TITLE
chromecast json.decoder exception in 0.1.647

### ISSUE THREAD

**Issue by tsadan** [fhempy/fhempy#147]
Since update to 0.1.647, chromecast devices are offline. 
fhempy log shows:

`2023-04-18 11:15:12,457 - INFO     - fhempy.lib.fhem_pythonbinding: Restart initiated...
2023-04-18 11:15:12,460 - INFO     - fhempy.lib.fhem_pythonbinding: All modules successfully undefined!
2023-04-18 11:15:12,461 - INFO     - websockets.server: server closing
2023-04-18 11:15:22,470 - INFO     - websockets.server: connection closed
2023-04-18 11:15:22,470 - INFO     - websockets.server: server closed
2023-04-18 11:15:22,471 - INFO     - fhempy.lib.fhem_pythonbinding: Exit 1
2023-04-18 11:15:22,835 - INFO     - fhempy.lib.fhem_pythonbinding: Starting fhempy 0.1.647...
2023-04-18 11:15:22,837 - INFO     - fhempy.lib.fhem_pythonbinding: Waiting for FHEM connection
2023-04-18 11:15:22,848 - INFO     - websockets.server: server listening on 0.0.0.0:15733
2023-04-18 11:15:32,580 - INFO     - websockets.server: connection open
2023-04-18 11:15:32,580 - INFO     - fhempy.lib.fhem_pythonbinding: Incoming FHEM connection: 127.0.0.1
2023-04-18 11:15:33,272 - ERROR    - GCA_Keller: Exception raised by task: <Task finished name='Task-448' coro=<FhemModule._run_coro() done, defined at /opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/generic.py:216> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>
Traceback (most recent call last):
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/generic.py", line 224, in _handle_task_result
    task.result()
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/generic.py", line 218, in _run_coro
    await coro
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/googlecast/googlecast.py", line 216, in connect_spotipy
    if self.spotipy_pkce.get_cached_token() is None:
  File "/opt/fhem/.local/lib/python3.9/site-packages/spotipy/oauth2.py", line 987, in get_cached_token
    return self.validate_token(self.cache_handler.get_cached_token())
  File "/opt/fhem/.local/lib/python3.9/site-packages/spotipy/cache_handler.py", line 77, in get_cached_token
    token_info = json.loads(token_info_string)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`
This happens to all chromecast devices (chromecast audio, home mini, nest mini). I also upgrade from python 3.8 to 3.9 in ubuntu 20.04 and restartet.

Am I doing something wrong ?

**Comment by fhempy** [comment]
Can you please try to disable spotify and check if it works without?

**Comment by tsadan** [comment]
Right now I'm not quite sure if I can follow. How do I have to deactivate Spotify?
Do you mean unlink Spotify in Google Home App ?

**Comment by fhempy** [comment]
I assume that you have connected your spotify account within the googlecast device in FHEM. Nevertheless, just create a new googlecast device within FHEM and see if it works.

**Comment by tsadan** [comment]
Deleting the chromecast device causing the error (GCA_Keller) led to no mor error in the log, but still all chromecast devices are offline. That is also the case for a fresh defined chromecast device in fhem.
I'll delete all my chromecast devices tomorrow and recreate them in fhem and come back with the results.

**Comment by tsadan** [comment]
I deleted all chromecast devices from fhem and readded one of them, it doesn't come online. There are no log entries in fhempy log, in fhem logging I can find the commands to create the device:

```
Apr 19 14:31:40 NAS.tsadan.local FHEM_fhem[1211496] 3: fhempy v1.0.0 (googlecast: GCA_Wohnzimmer)
Apr 19 14:31:40 NAS.tsadan.local FHEM_event[1211497] global DEFINED GCA_Wohnzimmer
Apr 19 14:31:40 NAS.tsadan.local FHEM_event[1211498] global ATTR GCA_Wohnzimmer cmdIcon pause:rc_PAUSE play:rc_PLAY stop:rc_STOP next:rc_NEXT prev:rc_PREVIOUS
Apr 19 14:31:40 NAS.tsadan.local FHEM_event[1211499] global ATTR GCA_Wohnzimmer devStateIcon ^playing.*:rc_PLAY:pause ^paused.*:rc_PAUSE:play
Apr 19 14:31:40 NAS.tsadan.local FHEM_event[1211500] global ATTR GCA_Wohnzimmer group googlecast
Apr 19 14:31:40 NAS.tsadan.local FHEM_event[1211501] global ATTR GCA_Wohnzimmer icon gassistant
Apr 19 14:31:40 NAS.tsadan.local FHEM_event[1211502] global ATTR GCA_Wohnzimmer room FHEM->Chromecast,N**********g3**->EG->Wohnzimmer
Apr 19 14:31:40 NAS.tsadan.local FHEM_event[1211503] global ATTR GCA_Wohnzimmer speak_lang de
Apr 19 14:31:40 NAS.tsadan.local FHEM_event[1211504] global ATTR GCA_Wohnzimmer stateFormat state <p> Artist: mediaArtist - Titel: mediaTitle <br>Position: mediaCurrentPosPercent %</p>
Apr 19 14:31:40 NAS.tsadan.local FHEM_event[1211505] global ATTR GCA_Wohnzimmer webCmd volume:playFavorite 1:playFavorite 2:playFavorite 3:playFavorite 4:playFavorite 5:play:pause:stop:prev:next
```
And when I restart the fhempyserver, I can find this:
```
Apr 19 14:44:28 NAS.tsadan.local FHEM_event[1221233] pyBinding python: 3.9.5
Apr 19 14:44:28 NAS.tsadan.local FHEM_event[1221234] pyBinding hostname: NAS
Apr 19 14:44:28 NAS.tsadan.local FHEM_event[1221235] pyBinding version: 0.1.647
Apr 19 14:44:28 NAS.tsadan.local FHEM_event[1221236] pyBinding os: posix
Apr 19 14:44:28 NAS.tsadan.local FHEM_event[1221237] pyBinding release: 5.4.0-146-generic
Apr 19 14:44:28 NAS.tsadan.local FHEM_event[1221238] pyBinding system: Linux
Apr 19 14:44:28 NAS.tsadan.local FHEM_event[1221239] pyBinding version_release_notes: <html><a href="https://github.com/fhempy/fhempy/releases" target="_blank">Release Notes</a></html>
Apr 19 14:44:28 NAS.tsadan.local FHEM_event[1221240] pyBinding version_available: 0.1.647
Apr 19 14:44:28 NAS.tsadan.local FHEM_event[1221241] GCA_Wohnzimmer spotify_login: <html><a href="https://accounts.spotify.com/authorize?client_id=e92855a009e74eb69ba6609d3bfd7d96&response_type=code&redirect_uri=https%3A%2F%2Feurope-west1-fhem-ga-connector.cloudfunctions.net%2Fcodelanding%2Fstart&code_challenge_method=S256&code_challenge=JfivqWWKBIRxhsvqORejXpe9JRVSXPMWLD3aXPxa42I&scope=user-read-recently-played+user-top-read+user-read-playback-position+user-read-playback-state+user-modify-playback-state+user-read-currently-playing+streaming+playlist-read-private+playlist-read-collaborative+user-follow-read+user-library-read+user-read-email+user-read-private" target="_blank">Connect Spotify account (new window/tab)</a><br></html>
Apr 19 14:44:28 NAS.tsadan.local FHEM_event[1221242] GCA_Wohnzimmer spotify_user: ****** (******@******.de)
```
Where does the Spotify part come from ? I fhem, I can't find a definition for that. To provide information from my browser, I used a private browser window while creating the device.

There seems to be no communication with the chromecast devices.

**Comment by fhempy** [comment]
GCA_Wohnzimmer reports a spotify user email as well, therefore I assume that you have configured it once. Can you please try a complete new one and provide logs?

**Comment by fhempy** [comment]
Please set verbose 5 for the test device and see the fhempy log.

**Comment by tsadan** [comment]
I set verbose 5 for test device, no further information. I set verbose 5 also to fhempyserver_15733 and byBindung, also no output. Then I did a set volume for test device, this led to this messages:
```
2023-04-19 20:51:59,703 - ERROR    - fhempy.lib.fhem_pythonbinding: Failed to execute function Set: Traceback (most recent call last):
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/fhem_pythonbinding.py", line 385, in handle_function
    ret = await self.execute_function(hash, fhem_reply_done, nmInstance)
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/fhem_pythonbinding.py", line 484, in execute_function
    ret = await asyncio.wait_for(
  File "/usr/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/generic.py", line 208, in Set
    return await utils.handle_set(self._conf_set, self, hash, args, argsh)
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/utils.py", line 335, in handle_set
    return await fct_call(hash, final_params)
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/googlecast/googlecast.py", line 256, in set_stop
    self.cast.media_controller.stop()
AttributeError: 'NoneType' object has no attribute 'media_controller'
 with hash: {'argsh': {}, 'function': 'Set', 'defargs': ['test', 'fhempy', 'googlecast', 'Wohnz
immer'], 'defargsh': {}, 'NAME': 'test', 'id': 88315856, 'PYTHONTYPE': 'googlecast', 'args': ['test', 'stop'], 'msgtype': 'function', 'FHEMPYTYPE': 'googlecast'}
2023-04-19 21:59:21,093 - ERROR    - fhempy.lib.fhem_pythonbinding: Failed to execute function Set: Traceback (most recent call last):
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/fhem_pythonbinding.py", line 385, in handle_function
    ret = await self.execute_function(hash, fhem_reply_done, nmInstance)
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/fhem_pythonbinding.py", line 484, in execute_function
    ret = await asyncio.wait_for(
  File "/usr/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/generic.py", line 208, in Set
    return await utils.handle_set(self._conf_set, self, hash, args, argsh)
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/utils.py", line 335, in handle_set
    return await fct_call(hash, final_params)
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/googlecast/googlecast.py", line 299, in set_volume
    self.cast.set_volume(vol / 100)
AttributeError: 'NoneType' object has no attribute 'set_volume'
 with hash: {'args': ['test', 'volume', '0'], 'PYTHONTYPE': 'googlecast', 'id': 91888325, 'NAME': 'test', 'defargs': ['test', 'fhempy', 'googlecast', 'Wohnzimmer'], 'defargsh': {}, 'function': 'Set', 'argsh': {}, 'FHEMPYTYPE': 'googlecast', 'msgtype': 'function'}
```
For me it still looks like, there is no communication between test device and server. When I remember it right, a few seconds after defining a googlecast device, some data is flowing between the device and fhem and the fhem device is 'filled' with some readings / internals /etc. This seems not to happen with the newly created test device.

I attached a file with the logging of fhempy, byBinding and test. At 20:41 the device was created, from 21:54 on, verbose 5 has been set. At 21:59 I tried to set the volume on test device.

Hope that helps ?

[fhempy-debug_20230420.log](https://github.com/fhempy/fhempy/files/11284403/fhempy-debug_20230420.log)

**Comment by fhempy** [comment]
As long as the device wasn't found on the network, no communication channel is established. fhempy (actually the pychromecast lib) tries to discover googlecast devices on the network via mDNS. As long as the device was not found, e.g. it didn't respond to a search via mDNS, the communication won't be setup.

Please try the following example code from pychromecast:
https://github.com/home-assistant-libs/pychromecast#how-to-use

Just open a Python 3 console with
```
sudo -u fhem bash
python3
```
and copy&paste one line after the other and check at which line you receive a wrong result.

**Comment by tsadan** [comment]
OK, with that tipp, I found out the root cause: My server runnning fhem and fhempy does not 'see' the cast devices with mdns, my other linux hosts do. 
So thank you very much for pointing me in the right direction ! 
I'll now try to figure out, why my server doesn't see the cast devices (while it sees others like a fritzbox i.e.). I'll close the issue.
