### ISSUE TITLE
fhempy Tuya local bekommt Werte-Updates der Tuya Geräte nach Offline-Online Wechsel nicht mit

### ISSUE THREAD

**Issue by StefanGitter** [fhempy/fhempy#167]
Hi,

nachdem ein Tuya Gerät Offline war und kurz vor dem Senden der Werte-Updates wieder Online geht, bekommt fhempy Tuya local Werte-Updates der Tuya Geräte nicht mit.

Ich kann das sehr gut mit meinem Kontaktsensor reproduzieren: Wenn dieser einige Minuten ohne Bewegung auf dem Tisch liegt, geht er Offline. Wenn ich dann den Kontakt entferne, geht er Online und sendet ein Update des Kontaktstatus. Das ist im tuya.com Log des Geräts zu sehen, fhempy_local zeigt aber keine Veränderung (immer noch Reading doorcontact_state=on). Erst wenn ich den Kontakt innerhalb kurzer Zeit wieder dran mache und wieder weg, also wenn das Gerät erneut Werte-Updates sendet, bekommt das fhempy_local mit (Reading  doorcontact_state=off).

tuya.com Gerätelog:
2023-06-28 21:16:48	Device restart	Device restart	power off reboot	device itself	
2023-06-28 21:16:47	Report	Door Sensor	ON	device itself	
2023-06-28 21:16:44	Report	Door Sensor	off	device itself	==> fhempy_local: erfolgreiches Update des doorcontact_state
2023-06-28 21:16:40	Report	Door Sensor	ON	device itself	
2023-06-28 21:16:39	Report	Door Sensor	off	device itself	==> fhempy_local: kein Update des doorcontact_state
2023-06-28 21:16:39	Online	Online		device itself	
2023-06-28 21:12:18	Offline	Offline	keepalive_timeout	device itself

Der Tuya Kontaktsensor ist in FHEM folgendermaßen definiert:

Internals:
   DEF        `tuya <geheim><geheime IP> 3.3 <geheim> <geheim>` 
   DEVICEID   `<geheim>`
   FHEMPYTYPE tuya
   FUUID      `<geheim>`
   IODev      fhempy_local
   NAME       `tuya_local_<geheim>`
   NR         629
   PYTHONTYPE tuya
   STATE      `<b>Türkontakt: on<br/>Batterie: 24.0%`
   TYPE       fhempy
   eventCount 85
   READINGS:
     2023-06-26 11:40:51   active_time     1687772310
     2023-06-28 09:53:01   battery_percentage 24.0
     2023-06-26 11:40:51   biz_type        18
     2023-06-26 11:40:51   category        mcs
     2023-06-26 11:40:51   create_time     1687185701
     2023-06-28 21:16:47   doorcontact_state on
     2023-06-26 11:40:51   icon            smart/icon/bay1624869296421wDFy/36fa2717304f55b8a2999f5b8a469109.png
     2023-06-26 11:40:51   id              `<geheim>`
     2023-06-26 11:40:51   ip              `<geheim>`
     2023-06-26 11:40:51   lat             49.3100
     2023-06-26 11:40:51   local_key       `<geheim>`
     2023-06-26 11:40:51   lon             8.8300
     2023-06-26 11:40:51   name            Contact Sensor 3
     2023-06-27 17:53:33   online          1
     2023-06-26 11:40:51   owner_id        `<geheim>`
     2023-06-26 11:40:51   product_id      qxu3flpqjsc1kqu3
     2023-06-26 11:40:51   product_name    Contact Sensor
     2023-06-27 17:53:39   state           ready
     2023-06-26 11:40:51   sub             0
     2023-06-26 11:40:51   time_zone       +02:00
     2023-06-26 11:40:51   uid             `<geheim>`
     2023-06-26 11:40:51   update_time     1687772388
     2023-06-26 11:40:51   uuid            `<geheim>`
   args:
     tuya_local_`<geheim>`
     fhempy
     tuya
     `<geheim>`
     `<geheim>`
     `<geheime` IP>
     3.3
     `<geheim>`
     `<geheim>`
   argsh:
Attributes:
   alias      Contact Sensor 3
   dp_01      doorcontact_state
   dp_02      battery_percentage
   group      tuya
   localkey   `<geheim>`
   room       fhempy
   stateFormat `<b>Türkontakt: doorcontact_state<br/>Batterie: battery_percentage%`
   tuya_spec_functions []
   tuya_spec_status `[{'code': 'doorcontact_state', 'dp_id': 1, 'type': 'Boolean', 'values': {}}, {'code': 'battery_percentage', 'dp_id': 2, 'type': 'Integer', 'values': {'unit': '%', 'min': 0, 'max': 100, 'scale': 0, 'step': 1}}]`

Gruß
Stefan

**Comment by fhempy** [comment]
Tuya und batteriebetriebene WiFi Devices sind leider nicht das gelbe vom Ei. Wo möglich, empfehle ich batteriebetriebene Zigbee Devices zu nutzen. Das ist viel stabiler und schneller.

Die Devices gehen leider nur ganz kurz online, schicken die Daten an die Cloud und sind dann wieder offline. Ich versuche mit dem tuya Modul regelmäßig eine Verbindung zu den Devices aufzubauen um dann genau diesen Moment zu erwischen. Kannst du das Device mal in FHEM auf verbose 5 stellen und prüfen ob da was hilfreiches im Log kommt?

**Comment by StefanGitter** [comment]
Ja, dass batteriebetriebene Tuya WiFi Devices nicht so gut funktionieren habe ich leider zu spät gelesen. Ich hatte extra auf WIFI gesetzt, in der Hoffnung, dass dann die Einbindung in FHEM besser funktionieren würde.

Dass das Modul regelmäßig pollt hatte ich mir schon gedacht. Dass dadurch einzelne Werte-Updates ggf. nicht mitbekommen werden ist auch logisch. Allerdings scheint es in dem konkreten Fall immer das erste Werte-Update nach dem Aufwachen zu sein.

Hier mal ein fhempy.log mit verbose 5 beim Contact Sensor 3 (tuya_local_bf0903bdb134fbf494aplq):

2023-07-11 10:44:21,742 - INFO     - fhempy.lib.fhem_pythonbinding: Starting fhempy 0.1.660...
2023-07-11 10:44:21,744 - INFO     - fhempy.lib.fhem_pythonbinding: Waiting for FHEM connection
2023-07-11 10:44:21,808 - INFO     - websockets.server: server listening on 0.0.0.0:15733
2023-07-11 10:44:31,096 - INFO     - websockets.server: connection open
2023-07-11 10:44:31,098 - INFO     - fhempy.lib.fhem_pythonbinding: Incoming FHEM connection: 127.0.0.1
2023-07-11 10:44:36,254 - ERROR    - websocket: Handshake status 401 Unauthorized -+-+- {'x-request-id': 'd836b878a1bc4e30b79e6f4b294276f3', 'x-protected-by': 'Tuya-Sec', 'cache-control': 'must-revalidate,no-cache,no-store', 'content-type': 'text/html;charset=iso-8859-1', 'content-length': '621', 'server': 'Jetty(9.4.35.v20201120)'} -+-+- b'<html>\n<head>\n<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>\n<title>Error 401 Authentication required</title>\n</head>\n<body><h2>HTTP ERROR 401 Authentication required</h2>\n<table>\n<tr><th>URI:</th><td>/ws/v2/consumer/persistent/qe95r4g7y9xutx8gtxgv/out/event/qe95r4g7y9xutx8gtxgv-sub</td></tr>\n<tr><th>STATUS:</th><td>401</td></tr>\n<tr><th>MESSAGE:</th><td>Authentication required</td></tr>\n<tr><th>SERVLET:</th><td>org.apache.pulsar.websocket.WebSocketConsumerServlet-1fde4f40</td></tr>\n</table>\n<hr><a href="https://eclipse.org/jetty">Powered by Jetty:// 9.4.35.v20201120</a><hr/>\n\n</body>\n</html>\n' - goodbye
2023-07-11 10:44:38,057 - ERROR    - tuya_cloud_connector: Please activate OpenPulsar: https://developer.tuya.com/en/docs/iot/subscribe-mq?id=Kavqcrvckbh9h
2023-07-11 10:44:39,498 - ERROR    - tuya_local_bfae0c082661b72241sewt: Failed to connect to device
Traceback (most recent call last):
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/tuya/tuya.py", line 563, in setup_connection
    self._connected_device = await asyncio.wait_for(connect_fct, timeout=15)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/opt/fhem/.local/lib/python3.9/site-packages/aiotinytuya/__init__.py", line 206, in connect
    await device.start_socket()
  File "/opt/fhem/.local/lib/python3.9/site-packages/aiotinytuya/core.py", line 917, in start_socket
    raise ex
  File "/opt/fhem/.local/lib/python3.9/site-packages/aiotinytuya/core.py", line 894, in start_socket
    self.reader, self.writer = await asyncio.open_connection(
  File "/usr/lib/python3.9/asyncio/streams.py", line 52, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.178.144', 6668)
2023-07-11 10:44:39,524 - ERROR    - tuya_local_bf1eb99456dde53846bf6z: Failed to connect to device
Traceback (most recent call last):
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/tuya/tuya.py", line 563, in setup_connection
    self._connected_device = await asyncio.wait_for(connect_fct, timeout=15)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/opt/fhem/.local/lib/python3.9/site-packages/aiotinytuya/__init__.py", line 206, in connect
    await device.start_socket()
  File "/opt/fhem/.local/lib/python3.9/site-packages/aiotinytuya/core.py", line 917, in start_socket
    raise ex
  File "/opt/fhem/.local/lib/python3.9/site-packages/aiotinytuya/core.py", line 894, in start_socket
    self.reader, self.writer = await asyncio.open_connection(
  File "/usr/lib/python3.9/asyncio/streams.py", line 52, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.178.121', 6668)
2023-07-11 10:44:51,343 - ERROR    - tuya_local_bf0903bdb134fbf494aplq: Failed to connect to device
Traceback (most recent call last):
  File "/opt/fhem/.local/lib/python3.9/site-packages/aiotinytuya/__init__.py", line 206, in connect
    await device.start_socket()
  File "/opt/fhem/.local/lib/python3.9/site-packages/aiotinytuya/core.py", line 894, in start_socket
    self.reader, self.writer = await asyncio.open_connection(
  File "/usr/lib/python3.9/asyncio/streams.py", line 52, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/tuya/tuya.py", line 563, in setup_connection
    self._connected_device = await asyncio.wait_for(connect_fct, timeout=15)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-07-11 10:45:15,205 - DEBUG    - tuya_local_bf0903bdb134fbf494aplq: handle type Boolean for dp_id 1 with value False
2023-07-11 10:45:15,408 - DEBUG    - tuya_local_bf0903bdb134fbf494aplq: handle type Boolean for dp_id 1 with value True
2023-07-11 10:45:18,128 - DEBUG    - tuya_local_bf0903bdb134fbf494aplq: handle type Boolean for dp_id 1 with value True
2023-07-11 10:45:21,300 - DEBUG    - tuya_local_bf0903bdb134fbf494aplq: handle type Boolean for dp_id 1 with value False
2023-07-11 10:45:25,675 - DEBUG    - tuya_local_bf0903bdb134fbf494aplq: handle type Boolean for dp_id 1 with value True
2023-07-11 10:45:32,531 - DEBUG    - tuya_local_bf0903bdb134fbf494aplq: handle type Boolean for dp_id 1 with value False
2023-07-11 10:45:34,535 - DEBUG    - tuya_local_bf0903bdb134fbf494aplq: handle type Boolean for dp_id 1 with value True
2023-07-11 10:45:35,941 - DEBUG    - tuya_local_bf0903bdb134fbf494aplq: handle type Boolean for dp_id 1 with value False
2023-07-11 10:45:37,996 - DEBUG    - tuya_local_bf0903bdb134fbf494aplq: handle type Boolean for dp_id 1 with value True
2023-07-11 10:53:24,134 - DEBUG    - tuya_local_bf0903bdb134fbf494aplq: handle type Boolean for dp_id 1 with value True
2023-07-11 10:53:24,702 - DEBUG    - tuya_local_bf0903bdb134fbf494aplq: handle type Boolean for dp_id 1 with value False
2023-07-11 10:53:27,831 - DEBUG    - tuya_local_bf0903bdb134fbf494aplq: handle type Boolean for dp_id 1 with value True
2023-07-11 10:54:03,079 - DEBUG    - tuya_local_bf0903bdb134fbf494aplq: handle type Boolean for dp_id 1 with value True
2023-07-11 10:54:04,537 - DEBUG    - tuya_local_bf0903bdb134fbf494aplq: handle type Boolean for dp_id 1 with value False
2023-07-11 10:54:04,750 - DEBUG    - tuya_local_bf0903bdb134fbf494aplq: handle type Boolean for dp_id 1 with value True
2023-07-11 10:54:06,768 - DEBUG    - tuya_local_bf0903bdb134fbf494aplq: handle type Boolean for dp_id 1 with value False
2023-07-11 10:54:08,058 - DEBUG    - tuya_local_bf0903bdb134fbf494aplq: handle type Boolean for dp_id 1 with value True
2023-07-11 10:54:12,178 - DEBUG    - tuya_local_bf0903bdb134fbf494aplq: handle type Boolean for dp_id 1 with value True
