### ISSUE TITLE
SeatConnect Version 1.1.7 needed

### ISSUE THREAD

**Issue by herblecupra** [fhempy/fhempy#168]
Es wird das neuere SeatConnect Modul mit Version 1.1.7 benötigt. In 1.1.6 existiert ein API Problem durch Änderungen bei Seat/Cupra 
Könnt ihr das Updaten?

**Comment by fhempy** [comment]
Danke für den Hinweis, ist aktualisiert.

**Comment by TorstenSothmann** [comment]
Hallo, gibt es bei Cupra etwas zu beachten? Ich bekommen folgenden Fehler:
2023-07-11 08:39:47,751 - INFO     - fhempy.lib.pkg_installer: Attempting install of seatconnect==1.1.7
2023-07-11 08:39:57,927 - INFO     - fhempy.lib.pkg_installer: Successfully installed seatconnect==1.1.7 update!
2023-07-11 08:40:01,859 - INFO     - seatconnect.connection: Init Seat Connect library, version 1.1.7
2023-07-11 08:40:01,860 - INFO     - seatconnect.connection: Initiating new login
2023-07-11 08:40:04,347 - ERROR    - Cupra: Exception raised by task: <Task finished coro=<FhemModule._run_coro() done, defined at /opt/fhem/.local/lib/python3.7/site-packages/fhempy/lib/generic.py:216> exception=AttributeError("'NoneType' object has no attribute 'get'")>
Traceback (most recent call last):
  File "/opt/fhem/.local/lib/python3.7/site-packages/fhempy/lib/generic.py", line 224, in _handle_task_result
    task.result()
  File "/opt/fhem/.local/lib/python3.7/site-packages/fhempy/lib/generic.py", line 218, in _run_coro
    await coro
  File "/opt/fhem/.local/lib/python3.7/site-packages/fhempy/lib/seatconnect/seatconnect.py", line 54, in start_login
    await connection.get_vehicles()
  File "/opt/fhem/.local/lib/python3.7/site-packages/seatconnect/connection.py", line 704, in get_vehicles
    if legacy_vehicles.get('userVehicles', {}).get('vehicle', False):
AttributeError: 'NoneType' object has no attribute 'get'

Falls unerwünscht bitte löschen. Danke
