### ISSUE TITLE
AttributeError: 'googlecast' object has no attribute 'spotify_access_token'

### ISSUE THREAD

**Issue by jfmennedy** [fhempy/fhempy#196]
Hi Dominik, i am trying to play sportify, but it wont start. in the log i got AttributeError: 'googlecast' object has no attribute 'spotify_access_token'.
sp_dc and sp_key are set and spotify user is logged in...

2023-09-26 08:19:20,564 - ERROR    - Google_Home_Mini_Iona: Exception raised by task: <Task finished name='Task-168510' coro=<FhemModule._run_coro() done, defined at /opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/generic.py:216> exception=AttributeError("'googlecast' object has no attribute 'spotify_access_token'")>
Traceback (most recent call last):
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/generic.py", line 224, in _handle_task_result
    task.result()
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/generic.py", line 218, in _run_coro
    await coro
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/googlecast/googlecast.py", line 436, in playSpotify
    if self.spotify_access_token is None:
AttributeError: 'googlecast' object has no attribute 'spotify_access_token'

**Comment by tsadan** [comment]
Hi,
same for me, also authcode for Spotify has been set successfully.
```
AttributeError: 'googlecast' object has no attribute 'spotify_access_token'
2023-10-07 11:14:11,475 - ERROR    - GCA_Wohnzimmer: Exception raised by task: <Task finished name='Task-35499' coro=<FhemModule._run_coro() done, defined at /opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/generic.py:216> exception=AttributeError("'googlecast' object has no attribute 'spotify_access_token'")>
Traceback (most recent call last):
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/generic.py", line 224, in _handle_task_result
    task.result()
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/generic.py", line 218, in _run_coro
    await coro
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/googlecast/googlecast.py", line 436, in playSpotify
    if self.spotify_access_token is None:
AttributeError: 'googlecast' object has no attribute 'spotify_access_token'
```

**Comment by fhempy** [comment]
Please try the latest version 0.1.670.

**Comment by tsadan** [comment]
I updated to 0.1.670 and tried playlist links as well as songs directly. I requested a new authcode and reentered sp_dc and sp_key. This is the output in the log:
```
2023-10-08 23:47:12,406 - ERROR    - pychromecast.socket_client: [Wohnzimmer(192.168.35.43):8009] Exception caught while sending message to controller SpotifyController: Message urn:x-c
ast:com.spotify.chromecast.secure.v1 from d914fc7a-9da4-4b1d-839c-32b0fd741987 to sender-0: {'type': 'getInfoResponse', 'payload': {'remoteName': 'Wohnzimmer', 'deviceID': 'fa9f7342e68d
99adc4b9692a825c0fc9', 'deviceAPI_isGroup': False, 'version': '2.9.0', 'publicKey': 'empty', 'deviceType': 'cast_audio', 'brandDisplayName': 'google', 'modelDisplayName': 'Chromecast_Au
dio', 'libraryVersion': '5.31.4', 'resolverVersion': '1', 'groupStatus': 'NONE', 'tokenType': 'accesstoken', 'clientID': 'd7df0887fb71494ea994202cb473eae7', 'productID': 0, 'scope': 'st
reaming', 'availability': '', 'spotifyError': 0, 'status': 101, 'statusString': 'OK'}}
Traceback (most recent call last):
  File "/opt/fhem/.local/lib/python3.9/site-packages/requests/models.py", line 960, in json
    return complexjson.loads(self.content.decode(encoding), **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
  File "/usr/lib/python3/dist-packages/simplejson/scanner.py", line 79, in scan_once
    return _scan_once(string, idx)
  File "/usr/lib/python3/dist-packages/simplejson/scanner.py", line 70, in _scan_once
    raise JSONDecodeError(errmsg, string, idx)
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/fhem/.local/lib/python3.9/site-packages/pychromecast/socket_client.py", line 719, in _route_message
    handled = handler.receive_message(message, data)
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/googlecast/spotcast/spotify_controller.py", line 64, in receive_message
    json_resp = response.json()
  File "/opt/fhem/.local/lib/python3.9/site-packages/requests/models.py", line 968, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-10-08 23:47:22,985 - ERROR    - GCA_Wohnzimmer: Failed to play spotify track
Traceback (most recent call last):
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/googlecast/googlecast.py", line 448, in playSpotify
    await utils.run_blocking(functools.partial(sp.launch_app))
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/utils.py", line 72, in run_blocking
    return await asyncio.get_event_loop().run_in_executor(pool, function)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/googlecast/spotcast/spotify_controller.py", line 116, in launch_app
    raise LaunchError(
pychromecast.error.LaunchError: Timeout when waiting for status response from Spotify app
```
