### ISSUE TITLE
Skoda Connect: Token exchange failed. Request status: 410

### ISSUE THREAD

**Issue by jowiemann** [fhempy/fhempy#253]
Hallo,

`[code]define fhempy_local BindingsIo fhempy
attr fhempy_local devStateIcon {      my $attr_ver = "1.1.0";;;;      my $status_img = "10px-kreis-gruen";;;;      my $status_txt = "connected";;;;      my $ver = ReadingsVal($name, "version", "-");;;;      my $ver_available = ReadingsVal($name, "version_available", $ver);;;;      my $update_icon = "";;;;      my $refresh_img = "refresh";;;;      my $refresh_txt = "Update fhempy";;;;      if ($ver_available ne $ver) {        $refresh_img = "refresh\@orange";;;;        $refresh_txt = "Version ".$ver_available." available for update";;;;      }      if (ReadingsVal($name, "state", "disconnected") eq "disconnected") {        $status_img = "10px-kreis-rot";;;;        $status_txt = "disconnected";;;;      }      $update_icon = "<a  href=\"/fhem?cmd.dummy=set $name update&XHR=1\" title=\"Start ".$ver_available." update\">".FW_makeImage($refresh_img, $refresh_txt)."</a>";;;;      my $restart_icon = "<a  href=\"/fhem?cmd.dummy=set $name restart&XHR=1\" title=\"Restart fhempy\">".FW_makeImage("control_reboot")."</a>";;;;      "<div><a>".FW_makeImage($status_img, $status_txt)."</a><a> ".$ver." </a>".$update_icon.$restart_icon."</div>"    }
attr fhempy_local group fhempy
attr fhempy_local icon file_json-ld2
attr fhempy_local room System
#   BindingType fhempy
#   DEF        fhempy
#   DeviceName ws:127.0.0.1:15733
#   FD         31
#   FUUID      657c41c8-f33f-0b39-6889-aa5e7a9a7029fb6f
#   IP         127.0.0.1
#   NAME       fhempy_local
#   NR         750
#   NTFY_ORDER 50-fhempy_local
#   PARTIAL    
#   PORT       15733
#   STATE      opened
#   TYPE       BindingsIo
#   WEBSOCKET  1
#   binary     1
#   connecttime 1702644257.70106
#   devioLoglevel 0
#   eventCount 33
#   installing 0
#   localBinding 1
#   nextOpenDelay 10
#   prev_error 
#   READINGS:
#     2023-12-15 13:42:07   hostname        raspberrypi
#     2023-12-15 13:42:07   os              posix
#     2023-12-15 13:42:07   python          3.9.2
#     2023-12-15 13:42:07   release         5.10.103-v7+
#     2023-12-15 13:44:17   state           opened
#     2023-12-15 13:42:07   system          Linux
#     2023-12-15 13:42:07   version         0.1.684
#     2023-12-18 01:44:19   version_available 0.1.689
#     2023-12-18 01:44:19   version_release_notes <html><a href="https://github.com/fhempy/fhempy/releases" target="_blank">Release Notes</a></html>
#   args:
#     fhempy_local
#     BindingsIo
#     fhempy
#   hmccu:
#   messages:
#     0:
#
setstate fhempy_local opened
setstate fhempy_local 2023-12-15 13:42:07 hostname raspberrypi
setstate fhempy_local 2023-12-15 13:42:07 os posix
setstate fhempy_local 2023-12-15 13:42:07 python 3.9.2
setstate fhempy_local 2023-12-15 13:42:07 release 5.10.103-v7+
setstate fhempy_local 2023-12-15 13:44:17 state opened
setstate fhempy_local 2023-12-15 13:42:07 system Linux
setstate fhempy_local 2023-12-15 13:42:07 version 0.1.684
setstate fhempy_local 2023-12-18 01:44:19 version_available 0.1.689
setstate fhempy_local 2023-12-18 01:44:19 version_release_notes <html><a href="https://github.com/fhempy/fhempy/releases" target="_blank">Release Notes</a></html>
[/code]`

ich bekomme seid einer Woche folgenden Fehler:

```
skodaconnect.exceptions.SkodaException: Token exchange failed. Request status: 410
    raise SkodaException(f'Token exchange failed. Request status: {req.status}')
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/skodaconnect/connection.py", line 348, in _authorize
    return await self._authorize('technical')
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/skodaconnect/connection.py", line 196, in doLogin
    while await connection.doLogin() is False:
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/fhempy/lib/skodaconnect/skodaconnect.py", line 79, in start_login
    await coro
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/fhempy/lib/generic.py", line 218, in _run_coro
    task.result()
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/fhempy/lib/generic.py", line 224, in _handle_task_result
Traceback (most recent call last):
2023-12-17 16:10:12,848 - ERROR    - Kodiaq: Exception raised by task: <Task finished name='Task-283' coro=<FhemModule._run_coro() done, defined at /opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/fhempy/lib/generic.py:216> exception=SkodaException('Token exchange failed. Request status: 410')>
2023-12-17 16:10:12,847 - ERROR    - skodaconnect.connection: Token exchange failed. Request status: 410
2023-12-17 16:10:11,650 - ERROR    - fhempy.lib.fhem_pythonbinding: <<< 89769458 3669.79ms: {'argsh': {}, 'FHEMPYTYPE': 'skodaconnect', 'defargs': ['Kodiaq', 'fhempy', 'skodaconnect', 'jowiemann@debitel.net', 'Mein5(Skoda6)', '1156'], 'NAME': 'Kodiaq', 'PYTHONTYPE': 'skodaconnect', 'id': 89769458, 'msgtype': 'function', 'defargsh': {}, 'args': ['Kodiaq', 'fhempy', 'skodaconnect', 'jowiemann@debitel.net', 'Mein5(Skoda6)', '1156'], 'function': 'Define', 'finished': 1, 'returnval': ''}
2023-12-17 16:10:11,639 - INFO     - skodaconnect.connection: Initiating new login
2023-12-17 16:10:11,637 - INFO     - skodaconnect.connection: Unofficial Skoda Connect library, version 1.3.8
```

Grüße Jörg

**Comment by jfmennedy** [comment]
Hallo Jörg,
Mache bitte ein Update von fhempy. Du hat noch die Skodaconnect Version 1.3.8. Ist in der 1.3.9 behoben.

Gruss Jan

**Comment by jowiemann** [comment]
Hallo Jan,

 

danke für den Anstupser. Läuft wieder.

 

Grüße Jörg

 

Von: jfmennedy ***@***.***> 
Gesendet: Montag, 18. Dezember 2023 12:06
An: fhempy/fhempy ***@***.***>
Cc: jowiemann ***@***.***>; Author ***@***.***>
Betreff: Re: [fhempy/fhempy] Skoda Connect: Token exchange failed. Request status: 410 (Issue #253)

 

Hallo Jörg,
Mache bitte ein Update von fhempy. Du hat noch die Skodaconnect Version 1.3.8. Ist in der 1.3.9 behoben.

Gruss Jan
