### ISSUE TITLE
Error create FHEM devices out of the xiaomi_tokens module (ModuleNotFoundError: No module named 'miio')

### ISSUE THREAD

**Issue by tasisale** [fhempy/fhempy#285]
i have the newses version of fhempy and -> python 3.11.7.
the Token i get without error, afer add a device will get this:
--
Module failed to load: miio
Maybe you need to update fhempy on this or remote peer.

Stacktrace:
Traceback (most recent call last):
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/fhem_pythonbinding.py", line 336, in handle_function
    module_object = await self.import_module(hash)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/fhem_pythonbinding.py", line 573, in import_module
    module_object = await utils.run_blocking(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/utils.py", line 72, in run_blocking
    return await asyncio.get_event_loop().run_in_executor(pool, function)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/miio/miio.py", line 8, in <module>
    from miio.click_common import DeviceGroupMeta
ModuleNotFoundError: No module named 'miio'

**Comment by fhempy** [comment]
Can you please verify in the fhempy logfile if fhempy tried to install python-miio? That packages is actually missing, but should be installed automatically. I couldn't reproduce the bug in my Python 3.11 env.

**Comment by tasisale** [comment]
how i can check the log?

**Comment by fhempy** [comment]
You should find the file in /opt/fhem/log/fhempy*.log

**Comment by tasisale** [comment]
here are the logfiles from two random days.
[fhempy-2024-01-07.log](https://github.com/fhempy/fhempy/files/13854490/fhempy-2024-01-07.log)
--
[fhempy-2024-01-02.log](https://github.com/fhempy/fhempy/files/13854491/fhempy-2024-01-02.log)

**Comment by fhempy** [comment]
Please do not post the full debug log, as it might contain sensitive data.
Just test it again and check if there is an ERROR output in the log. I would also highly recommend to deactivate fhempy debug as the logs get very big otherwise.

**Comment by tasisale** [comment]
ok, sorry. have delete the files here.

--
`
[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: pip install --upgrade pip
[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: pip install --upgrade pip
2024-01-07 20:31:33,653 - DEBUG    - fhempy.lib.fhem_pythonbinding: add pip path: /opt/fhem/.local/lib/python3.11/site-packages
2024-01-07 20:31:33,654 - DEBUG    - fhempy.lib.fhem: <<< 43324517: {'awaitId': 43324517, 'NAME': 'miio_vacuum_575985373', 'msgtype': 'command', 'command': "readingsSingleUpdate($defs{'miio_vacuum_575985373'},'state','Installation finished. Please wait...',1)"}
2024-01-07 20:31:33,659 - DEBUG    - fhempy.lib.fhem_pythonbinding: >>> 54708895: {'NAME': 'miio_vacuum_575985373', 'argsh': {}, 'defargs': ['miio_vacuum_575985373', 'fhempy', 'miio', 'vacuum', '192.168.151.3', 'xxxxxxxxxxxxxxxxxxxxxxx'], 'function': 'Set', 'FHEMPYTYPE': 'miio', 'args': ['miio_vacuum_575985373', '?'], 'msgtype': 'function', 'id': 54708895, 'defargsh': {}, 'PYTHONTYPE': 'miio'}
2024-01-07 20:31:33,659 - DEBUG    - fhempy.lib.fhem_pythonbinding: <<< 54708895 0.24ms: {'NAME': 'miio_vacuum_575985373', 'argsh': {}, 'defargs': ['miio_vacuum_575985373', 'fhempy', 'miio', 'vacuum', '192.168.151.3', 'xxxxxxxxxxxxxxxxxxxxxxx'], 'function': 'Set', 'FHEMPYTYPE': 'miio', 'args': ['miio_vacuum_575985373', '?'], 'msgtype': 'function', 'id': 54708895, 'defargsh': {}, 'PYTHONTYPE': 'miio', 'finished': 1, 'returnval': ''}
2024-01-07 20:31:33,662 - DEBUG    - fhempy.lib.fhem_pythonbinding: >>> 56723665: {'function': 'Set', 'defargs': ['miio_vacuum_575985373', 'fhempy', 'miio', 'vacuum', '192.168.151.3', 'xxxxxxxxxxxxxxxxxxxxxxx'], 'NAME': 'miio_vacuum_575985373', 'argsh': {}, 'PYTHONTYPE': 'miio', 'defargsh': {}, 'id': 56723665, 'args': ['miio_vacuum_575985373', '?'], 'msgtype': 'function', 'FHEMPYTYPE': 'miio'}
2024-01-07 20:31:33,662 - DEBUG    - fhempy.lib.fhem_pythonbinding: <<< 56723665 0.19ms: {'function': 'Set', 'defargs': ['miio_vacuum_575985373', 'fhempy', 'miio', 'vacuum', '192.168.151.3', 'xxxxxxxxxxxxxxxxxxxxxxx'], 'NAME': 'miio_vacuum_575985373', 'argsh': {}, 'PYTHONTYPE': 'miio', 'defargsh': {}, 'id': 56723665, 'args': ['miio_vacuum_575985373', '?'], 'msgtype': 'function', 'FHEMPYTYPE': 'miio', 'finished': 1, 'returnval': ''}
2024-01-07 20:31:33,664 - DEBUG    - fhempy.lib.fhem: >>> 43324517 10.07ms: {'awaitId': 43324517, 'result': 'Installation finished. Please wait...', 'error': 0}
`

**Comment by tasisale** [comment]
`2024-01-07 20:33:57,284 - DEBUG    - fhempy.lib.fhem_pythonbinding: >>> 28107481: {'id': 28107481, 'defargsh': {}, 'PYTHONTYPE': 'miio', 'FHEMPYTYPE': 'miio', 'args': ['miio_vacuum_575985373', '?'], 'msgtype': 'function', 'function': 'Set', 'defargs': ['miio_vacuum_575985373', 'fhempy', 'miio', 'vacuum', '192.168.151.3', 'xxxxxxxxxxxxxxxxxxxxxxx'], 'NAME': 'miio_vacuum_575985373', 'argsh': {}}
2024-01-07 20:33:57,284 - DEBUG    - fhempy.lib.fhem_pythonbinding: <<< 28107481 0.18ms: {'id': 28107481, 'defargsh': {}, 'PYTHONTYPE': 'miio', 'FHEMPYTYPE': 'miio', 'args': ['miio_vacuum_575985373', '?'], 'msgtype': 'function', 'function': 'Set', 'defargs': ['miio_vacuum_575985373', 'fhempy', 'miio', 'vacuum', '192.168.151.3', 'xxxxxxxxxxxxxxxxxxxxxxx'], 'NAME': 'miio_vacuum_575985373', 'argsh': {}, 'finished': 1, 'returnval': ''}
2024-01-07 20:33:57,473 - DEBUG    - fhempy.lib.fhem_pythonbinding: >>> 52996607: {'FHEMPYTYPE': 'miio', 'msgtype': 'function', 'args': ['miio_vacuum_575985373', '?'], 'defargsh': {}, 'id': 52996607, 'PYTHONTYPE': 'miio', 'defargs': ['miio_vacuum_575985373', 'fhempy', 'miio', 'vacuum', '192.168.151.3', 'xxxxxxxxxxxxxxxxxxxxxxx'], 'argsh': {}, 'NAME': 'miio_vacuum_575985373', 'function': 'Set'}
2024-01-07 20:33:57,473 - DEBUG    - fhempy.lib.fhem_pythonbinding: <<< 52996607 0.18ms: {'FHEMPYTYPE': 'miio', 'msgtype': 'function', 'args': ['miio_vacuum_575985373', '?'], 'defargsh': {}, 'id': 52996607, 'PYTHONTYPE': 'miio', 'defargs': ['miio_vacuum_575985373', 'fhempy', 'miio', 'vacuum', '192.168.151.3', 'xxxxxxxxxxxxxxxxxxxxxxx'], 'argsh': {}, 'NAME': 'miio_vacuum_575985373', 'function': 'Set', 'finished': 1, 'returnval': ''}
`

**Comment by fhempy** [comment]
Ich sehe da nicht wirklich einen Fehler. Schalte bitte den debug Mode aus, das erzeugt sehr viel Traffic im Log (verbose=3 empfehle ich).

Funktioniert es nun noch immer nicht? Probier bitte mal und poste den Output
```
sudo -u fhem bash
source .fhempy/fhempy_venv/bin/activate
pip3 install python-miio
```

**Comment by fhempy** [comment]
I just did another test on my system with my vacuum. Please keep in mind that you need to change `vacuum` to `roborockvacuum` in the created define.

**Comment by tasisale** [comment]
i have tested it today again, the same error.
AHHHHH

**Comment by tasisale** [comment]
> source .fhempy/fhempy_venv/bin/activate


fhem@srvfhem:/home/fhemadmin$ source .fhempy/fhempy_venv/bin/activate
bash: .fhempy/fhempy_venv/bin/activate: Datei oder Verzeichnis nicht gefunden

**Comment by tasisale** [comment]
> pip3 install python-miio

`pip3 install python-miio
Traceback (most recent call last):
  File "/usr/bin/pip3", line 11, in <module>
    load_entry_point('pip==20.0.2', 'console_scripts', 'pip3')()
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 73, in m                                                                                                    ain
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/__init__.py", line                                                                                                     96, in create_command
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line                                                                                                     24, in <module>
    from pip._internal.cli.req_command import RequirementCommand
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 1                                                                                                    5, in <module>
    from pip._internal.index.package_finder import PackageFinder
  File "/usr/lib/python3/dist-packages/pip/_internal/index/package_finder.py", l                                                                                                    ine 21, in <module>
    from pip._internal.index.collector import parse_links
  File "/usr/lib/python3/dist-packages/pip/_internal/index/collector.py", line 1                                                                                                    2, in <module>
    from pip._vendor import html5lib, requests
ImportError: cannot import name 'html5lib' from 'pip._vendor' (/usr/lib/python3/                                                                                                    dist-packages/pip/_vendor/__init__.py)
`

**Comment by fhempy** [comment]
Looks like html5lib can't be installed on your system. Try pip3 install html5lib

**Comment by tasisale** [comment]
> Looks like html5lib can't be installed on your system. Try pip3 install html5lib

ok, will install html5lib and test again, thx!

**Comment by tasisale** [comment]
ok, have done, but the same error.
sorry
--
`Module failed to load: miio
Maybe you need to update fhempy on this or remote peer.

Stacktrace:
Traceback (most recent call last):
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/fhem_pythonbinding.py", line 336, in handle_function
    module_object = await self.import_module(hash)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/fhem_pythonbinding.py", line 573, in import_module
    module_object = await utils.run_blocking(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/utils.py", line 72, in run_blocking
    return await asyncio.get_event_loop().run_in_executor(pool, function)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/miio/miio.py", line 8, in <module>
    from miio.click_common import DeviceGroupMeta
ModuleNotFoundError: No module named 'miio'`

**Comment by tasisale** [comment]
> sudo -u fhem bash
> source .fhempy/fhempy_venv/bin/activate
> pip3 install python-miio

i have now do this, but the error is show:
--
`Building wheels for collected packages: netifaces
  Building wheel for netifaces (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for netifaces (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      running bdist_wheel
      running build
      running build_ext
      checking for getifaddrs...found.
      checking for getnameinfo...found.
      checking for IPv6 socket IOCTLs...not found.
      checking for optional header files...netash/ash.h netatalk/at.h netax25/ax                                                                                        25.h neteconet/ec.h netipx/ipx.h netpacket/packet.h netrose/rose.h linux/atm.h l                                                                                        inux/llc.h linux/tipc.h.
      checking whether struct sockaddr has a length field...no.
      checking which sockaddr_xxx structs are defined...at ax25 in in6 ipx un ro                                                                                        se ash ec ll atmpvc atmsvc llc.
      checking for routing socket support...no.
      checking for sysctl(CTL_NET...) support...no.
      checking for netlink support...yes.
      will use netlink to read routing table
      building 'netifaces' extension
      x86_64-linux-gnu-gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall                                                                                         -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fP                                                                                        IC -DNETIFACES_VERSION=0.11.0 -DHAVE_GETIFADDRS=1 -DHAVE_GETNAMEINFO=1 -DHAVE_NE                                                                                        TASH_ASH_H=1 -DHAVE_NETATALK_AT_H=1 -DHAVE_NETAX25_AX25_H=1 -DHAVE_NETECONET_EC_                                                                                        H=1 -DHAVE_NETIPX_IPX_H=1 -DHAVE_NETPACKET_PACKET_H=1 -DHAVE_NETROSE_ROSE_H=1 -D                                                                                        HAVE_LINUX_ATM_H=1 -DHAVE_LINUX_LLC_H=1 -DHAVE_LINUX_TIPC_H=1 -DHAVE_SOCKADDR_AT                                                                                        =1 -DHAVE_SOCKADDR_AX25=1 -DHAVE_SOCKADDR_IN=1 -DHAVE_SOCKADDR_IN6=1 -DHAVE_SOCK                                                                                        ADDR_IPX=1 -DHAVE_SOCKADDR_UN=1 -DHAVE_SOCKADDR_ROSE=1 -DHAVE_SOCKADDR_ASH=1 -DH                                                                                        AVE_SOCKADDR_EC=1 -DHAVE_SOCKADDR_LL=1 -DHAVE_SOCKADDR_ATMPVC=1 -DHAVE_SOCKADDR_                                                                                        ATMSVC=1 -DHAVE_SOCKADDR_LLC=1 -DHAVE_PF_NETLINK=1 -I/opt/fhem/.fhempy/fhempy_ve                                                                                        nv/include -I/usr/include/python3.11 -c netifaces.c -o build/temp.linux-x86_64-c                                                                                        python-311/netifaces.o
      netifaces.c:1:10: fatal error: Python.h: Datei oder Verzeichnis nicht gefu                                                                                        nden
          1 | #include <Python.h>
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem wit                                                                                        h pip.
  ERROR: Failed building wheel for netifaces
Failed to build netifaces
ERROR: Could not build wheels for netifaces, which is required to install pyproj                                                                                        ect.toml-based projects
(fhempy_venv) fhem@srvfhem:/home/fhemadmin$
`
--

**Comment by tasisale** [comment]
i have now installed sudo apt-get install python3.11-dev and restart the NUC, now it will be show as "active".

thx and regards
simon

**Comment by fhempy** [comment]
Great, please make sure that you have installed all required packages as -dev is already part of it:
sudo apt install python3 python3-pip python3-dev python3-venv libffi-dev libssl-dev libjpeg-dev zlib1g-dev autoconf build-essential libglib2.0-dev libdbus-1-dev bluez libbluetooth-dev git libprotocol-websocket-perl
