### ISSUE TITLE
eq3bt - ubuntu - still unstable

### ISSUE THREAD

**Issue by JorinL** [fhempy/fhempy#314]
Hey there :-)

For Ubuntu the situation seems still a bit unstable - situation this morning/day:

```
Jan 24 13:52:08 homeland fhempy[2828011]: ERROR:Wohnzimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 13:52:45 homeland fhempy[2828011]: ERROR:Badezimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 13:53:38 homeland fhempy[2828011]: ERROR:Wohnzimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 13:54:15 homeland fhempy[2828011]: ERROR:Badezimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 13:55:08 homeland fhempy[2828011]: ERROR:Wohnzimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 13:55:45 homeland fhempy[2828011]: ERROR:Badezimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 13:56:38 homeland fhempy[2828011]: ERROR:Wohnzimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 13:57:15 homeland fhempy[2828011]: ERROR:Badezimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 13:58:08 homeland fhempy[2828011]: ERROR:Wohnzimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 13:58:45 homeland fhempy[2828011]: ERROR:Badezimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 13:59:38 homeland fhempy[2828011]: ERROR:Wohnzimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:00:15 homeland fhempy[2828011]: ERROR:Badezimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:01:08 homeland fhempy[2828011]: ERROR:Wohnzimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:01:45 homeland fhempy[2828011]: ERROR:Badezimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:02:38 homeland fhempy[2828011]: ERROR:Wohnzimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:03:15 homeland fhempy[2828011]: ERROR:Badezimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:04:08 homeland fhempy[2828011]: ERROR:Wohnzimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:04:45 homeland fhempy[2828011]: ERROR:Badezimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:05:38 homeland fhempy[2828011]: ERROR:Wohnzimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:06:15 homeland fhempy[2828011]: ERROR:Badezimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:07:08 homeland fhempy[2828011]: ERROR:Wohnzimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:07:45 homeland fhempy[2828011]: ERROR:Badezimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:08:38 homeland fhempy[2828011]: ERROR:Wohnzimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:09:15 homeland fhempy[2828011]: ERROR:Badezimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:10:08 homeland fhempy[2828011]: ERROR:Wohnzimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:10:45 homeland fhempy[2828011]: ERROR:Badezimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:11:38 homeland fhempy[2828011]: ERROR:Wohnzimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:12:15 homeland fhempy[2828011]: ERROR:Badezimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:13:08 homeland fhempy[2828011]: ERROR:Wohnzimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:13:45 homeland fhempy[2828011]: ERROR:Badezimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:14:38 homeland fhempy[2828011]: ERROR:Wohnzimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:15:15 homeland fhempy[2828011]: ERROR:Badezimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:16:08 homeland fhempy[2828011]: ERROR:Wohnzimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:16:45 homeland fhempy[2828011]: ERROR:Badezimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:17:38 homeland fhempy[2828011]: ERROR:Wohnzimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:18:15 homeland fhempy[2828011]: ERROR:Badezimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:19:08 homeland fhempy[2828011]: ERROR:Wohnzimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:19:45 homeland fhempy[2828011]: ERROR:Badezimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:20:38 homeland fhempy[2828011]: ERROR:Wohnzimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:21:15 homeland fhempy[2828011]: ERROR:Badezimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:22:08 homeland fhempy[2828011]: ERROR:Wohnzimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:22:45 homeland fhempy[2828011]: ERROR:Badezimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:23:38 homeland fhempy[2828011]: ERROR:Wohnzimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:24:15 homeland fhempy[2828011]: ERROR:Badezimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:25:08 homeland fhempy[2828011]: ERROR:Wohnzimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:25:45 homeland fhempy[2828011]: ERROR:Badezimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:26:38 homeland fhempy[2828011]: ERROR:Wohnzimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:27:15 homeland fhempy[2828011]: ERROR:Badezimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:28:08 homeland fhempy[2828011]: ERROR:Wohnzimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:28:45 homeland fhempy[2828011]: ERROR:Badezimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:29:38 homeland fhempy[2828011]: ERROR:Wohnzimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:30:15 homeland fhempy[2828011]: ERROR:Badezimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:31:08 homeland fhempy[2828011]: ERROR:Wohnzimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:31:45 homeland fhempy[2828011]: ERROR:Badezimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:32:38 homeland fhempy[2828011]: ERROR:Wohnzimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:33:15 homeland fhempy[2828011]: ERROR:Badezimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:34:08 homeland fhempy[2828011]: ERROR:Wohnzimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:34:45 homeland fhempy[2828011]: ERROR:Badezimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:35:39 homeland fhempy[2828011]: ERROR:Wohnzimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:36:15 homeland fhempy[2828011]: ERROR:Badezimmer_Thermostat:Timeout on update, retry in 60s
```

Commands (power off/power on/scan on/scan off) in bluetoothctl are no longer fullfilled.

Restart of fhempy:

```
Jan 24 14:37:53 homeland systemd[1]: Started fhempy.
Jan 24 14:38:34 homeland fhempy[188722]: ERROR:Wohnzimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:38:34 homeland fhempy[188722]: ERROR:Badezimmer_Thermostat:Timeout on update, retry in 60s
```

So no change - after the restart of bluetooth.service and restart of fhempy after that:

```
Jan 24 14:42:15 homeland systemd[1]: Started fhempy.
Jan 24 14:42:30 homeland fhempy[194161]: /home/jorin/.local/lib/python3.10/site-packages/fhempy/lib/core/bluetoothle.py:224: FutureWarning: BLEDevice.rssi is deprecated and will be removed in a future version of Bleak, use AdvertisementData.rssi instead
Jan 24 14:42:30 homeland fhempy[194161]:   self._dev_hash, "rssi", self._device.rssi, 1
Jan 24 14:42:31 homeland fhempy[194161]: /home/jorin/.local/lib/python3.10/site-packages/fhempy/lib/core/bluetoothle.py:224: FutureWarning: BLEDevice.rssi is deprecated and will be removed in a future version of Bleak, use AdvertisementData.rssi instead
Jan 24 14:42:31 homeland fhempy[194161]:   self._dev_hash, "rssi", self._device.rssi, 1
Jan 24 14:42:44 homeland fhempy[194161]: ERROR:Badezimmer_Thermostat:Failed to update, retry in 60s
Jan 24 14:42:44 homeland fhempy[194161]: Traceback (most recent call last):
Jan 24 14:42:44 homeland fhempy[194161]:   File "/home/jorin/.local/lib/python3.10/site-packages/fhempy/lib/eq3bt/eq3bt.py", line 187, in check_online
Jan 24 14:42:44 homeland fhempy[194161]:     await self.update_all()
Jan 24 14:42:44 homeland fhempy[194161]:   File "/home/jorin/.local/lib/python3.10/site-packages/fhempy/lib/eq3bt/eq3bt.py", line 205, in update_all
Jan 24 14:42:44 homeland fhempy[194161]:     await self.thermostat.update_all()
Jan 24 14:42:44 homeland fhempy[194161]:   File "/home/jorin/.local/lib/python3.10/site-packages/fhempy/lib/eq3bt/eq3bt.py", line 493, in update_all
Jan 24 14:42:44 homeland fhempy[194161]:     await super().query_schedule(day)
Jan 24 14:42:44 homeland fhempy[194161]:   File "/home/jorin/.local/lib/python3.10/site-packages/fhempy/lib/eq3bt/eq3btsmart.py", line 262, in query_schedule
Jan 24 14:42:44 homeland fhempy[194161]:     await self._conn.write_gatt_char(PROP_WRITE_HANDLE, value)
Jan 24 14:42:44 homeland fhempy[194161]:   File "/home/jorin/.local/lib/python3.10/site-packages/fhempy/lib/core/bluetoothle.py", line 270, in write_gatt_char
Jan 24 14:42:44 homeland fhempy[194161]:     await self._client.write_gatt_char(uuid, data)
Jan 24 14:42:44 homeland fhempy[194161]:   File "/home/jorin/.local/lib/python3.10/site-packages/bleak/__init__.py", line 659, in write_gatt_char
Jan 24 14:42:44 homeland fhempy[194161]:     await self._backend.write_gatt_char(char_specifier, data, response)
Jan 24 14:42:44 homeland fhempy[194161]:   File "/home/jorin/.local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 905, in write_gatt_char
Jan 24 14:42:44 homeland fhempy[194161]:     assert_reply(reply)
Jan 24 14:42:44 homeland fhempy[194161]:   File "/home/jorin/.local/lib/python3.10/site-packages/bleak/backends/bluezdbus/utils.py", line 22, in assert_reply
Jan 24 14:42:44 homeland fhempy[194161]:     raise BleakDBusError(reply.error_name, reply.body)
Jan 24 14:42:44 homeland fhempy[194161]: bleak.exc.BleakDBusError: [org.bluez.Error.Failed] Operation failed with ATT error: 0x0e (Unlikely Error)
Jan 24 14:42:44 homeland fhempy[194161]: ERROR:Badezimmer_Thermostat:Device disconnected, reconnect now
Jan 24 14:42:52 homeland fhempy[194161]: ERROR:Badezimmer_Thermostat:Device disconnected, reconnect now
Jan 24 14:42:57 homeland fhempy[194161]: ERROR:Badezimmer_Thermostat:Failed to connect
Jan 24 14:42:57 homeland fhempy[194161]: Traceback (most recent call last):
Jan 24 14:42:57 homeland fhempy[194161]:   File "/home/jorin/.local/lib/python3.10/site-packages/fhempy/lib/core/bluetoothle.py", line 180, in connect_loop
Jan 24 14:42:57 homeland fhempy[194161]:     await self.connect_once(timeout, max_retries)
Jan 24 14:42:57 homeland fhempy[194161]:   File "/home/jorin/.local/lib/python3.10/site-packages/fhempy/lib/core/bluetoothle.py", line 235, in connect_once
Jan 24 14:42:57 homeland fhempy[194161]:     await self._subscribe_notifies()
Jan 24 14:42:57 homeland fhempy[194161]:   File "/home/jorin/.local/lib/python3.10/site-packages/fhempy/lib/core/bluetoothle.py", line 258, in _subscribe_notifies
Jan 24 14:42:57 homeland fhempy[194161]:     services = self._client.services
Jan 24 14:42:57 homeland fhempy[194161]: AttributeError: 'NoneType' object has no attribute 'services'
Jan 24 14:43:50 homeland fhempy[194161]: ERROR:Badezimmer_Thermostat:Device disconnected, reconnect now
Jan 24 14:44:01 homeland fhempy[194161]: ERROR:Badezimmer_Thermostat:Device disconnected, reconnect now
Jan 24 14:44:04 homeland fhempy[194161]: ERROR:Badezimmer_Thermostat:Device disconnected, reconnect now
Jan 24 14:44:08 homeland fhempy[194161]: ERROR:Badezimmer_Thermostat:Failed to connect
Jan 24 14:44:08 homeland fhempy[194161]: Traceback (most recent call last):
Jan 24 14:44:08 homeland fhempy[194161]:   File "/home/jorin/.local/lib/python3.10/site-packages/fhempy/lib/core/bluetoothle.py", line 180, in connect_loop
Jan 24 14:44:08 homeland fhempy[194161]:     await self.connect_once(timeout, max_retries)
Jan 24 14:44:08 homeland fhempy[194161]:   File "/home/jorin/.local/lib/python3.10/site-packages/fhempy/lib/core/bluetoothle.py", line 235, in connect_once
Jan 24 14:44:08 homeland fhempy[194161]:     await self._subscribe_notifies()
Jan 24 14:44:08 homeland fhempy[194161]:   File "/home/jorin/.local/lib/python3.10/site-packages/fhempy/lib/core/bluetoothle.py", line 258, in _subscribe_notifies
Jan 24 14:44:08 homeland fhempy[194161]:     services = self._client.services
Jan 24 14:44:08 homeland fhempy[194161]: AttributeError: 'NoneType' object has no attribute 'services'
Jan 24 14:44:09 homeland fhempy[194161]: ERROR:Badezimmer_Thermostat:Device disconnected, reconnect now
Jan 24 14:44:14 homeland fhempy[194161]: ERROR:Badezimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:44:23 homeland fhempy[194161]: ERROR:Badezimmer_Thermostat:Device disconnected, reconnect now
Jan 24 14:44:27 homeland fhempy[194161]: ERROR:Badezimmer_Thermostat:Failed to connect
Jan 24 14:44:27 homeland fhempy[194161]: Traceback (most recent call last):
Jan 24 14:44:27 homeland fhempy[194161]:   File "/home/jorin/.local/lib/python3.10/site-packages/fhempy/lib/core/bluetoothle.py", line 234, in connect_once
Jan 24 14:44:27 homeland fhempy[194161]:     await self._client.connect()
Jan 24 14:44:27 homeland fhempy[194161]:   File "/home/jorin/.local/lib/python3.10/site-packages/bleak/__init__.py", line 531, in connect
Jan 24 14:44:27 homeland fhempy[194161]:     return await self._backend.connect(**kwargs)
Jan 24 14:44:27 homeland fhempy[194161]:   File "/home/jorin/.local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 263, in connect
Jan 24 14:44:27 homeland fhempy[194161]:     await self.get_services(
Jan 24 14:44:27 homeland fhempy[194161]:   File "/home/jorin/.local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 649, in get_services
Jan 24 14:44:27 homeland fhempy[194161]:     self.services = await manager.get_services(
Jan 24 14:44:27 homeland fhempy[194161]:   File "/home/jorin/.local/lib/python3.10/site-packages/bleak/backends/bluezdbus/manager.py", line 581, in get_services
Jan 24 14:44:27 homeland fhempy[194161]:     await self._wait_for_services_discovery(device_path)
Jan 24 14:44:27 homeland fhempy[194161]:   File "/home/jorin/.local/lib/python3.10/site-packages/bleak/backends/bluezdbus/manager.py", line 686, in _wait_for_services_discovery
Jan 24 14:44:27 homeland fhempy[194161]:     raise BleakError("failed to discover services, device disconnected")
Jan 24 14:44:27 homeland fhempy[194161]: bleak.exc.BleakError: failed to discover services, device disconnected
Jan 24 14:44:27 homeland fhempy[194161]: ERROR:Badezimmer_Thermostat:Device disconnected, reconnect now
Jan 24 14:44:51 homeland fhempy[194161]: ERROR:Badezimmer_Thermostat:Device disconnected, reconnect now
Jan 24 14:44:57 homeland fhempy[194161]: ERROR:Badezimmer_Thermostat:Device disconnected, reconnect now
Jan 24 14:45:02 homeland fhempy[194161]: ERROR:Badezimmer_Thermostat:Failed to connect
Jan 24 14:45:02 homeland fhempy[194161]: Traceback (most recent call last):
Jan 24 14:45:02 homeland fhempy[194161]:   File "/home/jorin/.local/lib/python3.10/site-packages/fhempy/lib/core/bluetoothle.py", line 180, in connect_loop
Jan 24 14:45:02 homeland fhempy[194161]:     await self.connect_once(timeout, max_retries)
Jan 24 14:45:02 homeland fhempy[194161]:   File "/home/jorin/.local/lib/python3.10/site-packages/fhempy/lib/core/bluetoothle.py", line 235, in connect_once
Jan 24 14:45:02 homeland fhempy[194161]:     await self._subscribe_notifies()
Jan 24 14:45:02 homeland fhempy[194161]:   File "/home/jorin/.local/lib/python3.10/site-packages/fhempy/lib/core/bluetoothle.py", line 258, in _subscribe_notifies
Jan 24 14:45:02 homeland fhempy[194161]:     services = self._client.services
Jan 24 14:45:02 homeland fhempy[194161]: AttributeError: 'NoneType' object has no attribute 'services'
Jan 24 14:45:42 homeland fhempy[194161]: ERROR:Badezimmer_Thermostat:Device disconnected, reconnect now
Jan 24 14:45:44 homeland fhempy[194161]: ERROR:Badezimmer_Thermostat:Timeout on update, retry in 60s
Jan 24 14:47:57 homeland fhempy[194161]: ERROR:Wohnzimmer_Thermostat:Device disconnected, reconnect now
Jan 24 14:48:00 homeland fhempy[194161]: ERROR:Badezimmer_Thermostat:Device disconnected, reconnect now
```

It is working again.

So it seems like something is getting the bt service to an end :-D

**Comment by fhempy** [comment]
I found one bug in the notification handling, but I don't think that it has something to do with this issue.

**Comment by JorinL** [comment]
We can always try :-D

**Comment by fhempy** [comment]
Hi, any news? 😄  Please let me know if it works for your, if so, you can close the issue. Thx!

**Comment by JorinL** [comment]
Will check asap - currently busy by businesstrip.
And somehow on closed networks :-D

**Comment by JorinL** [comment]
Seems to be working good :-)
