### ISSUE TITLE
eq3bt - why does my eq3bt fhem page not match the screenshot?

### ISSUE THREAD

**Issue by malcb** [fhempy/fhempy#325]
The screenshot with eq3bt does not match what I see, why?  It's a lot different so maybe I have a problem.  I see no list of schedule_X_Y, valve position is 0, desiredTemperature is 0, all comsumptions are 0, etc..  If I change the desiredTemperature (hint by clicking and pulling the value, NOT typing in a number, DOH did that take me a time to figure out!), then the number on the real part display changes and the valve moves.  Verbose is set to 5 and the fhempy log file is full of "DEBUG    - Eq3bt1: Querying schedule.." so it seems to be sending, just not getting anything back.

Any suggestions?

**Comment by malcb** [comment]
Update:,  I had in fhem.cfg "define fhempy_local BindingsIo 127.0.0.1:15733 fhempy" to get it to work (and maybe update).  I've changed that back to "define fhempy_local BindingsIo fhempy" and now I seem to get a bit more:

2024-02-04 19:14:16,617 - DEBUG    - Eq3bt1: Querying the device..
2024-02-04 19:14:46,626 - ERROR    - Eq3bt1: Timeout on update, retry in 60s
2024-02-04 19:15:06,805 - INFO     - Eq3bt1: Device found via adapter hci0
2024-02-04 19:15:46,667 - DEBUG    - Eq3bt1: start update_all
2024-02-04 19:15:46,673 - DEBUG    - Eq3bt1: Querying the device..
etc.

**Comment by malcb** [comment]
I've tried both with and without the PIN number.  in SSH bluetoothctl does not ask for a pin number when I tell it to pair.  Info shows that device has paired.  But if I run info in SSH when fhem is running bluetoothctl says it is not paired (should it say paired?).  The output from fhempy log is:

`Activating virtual environment...OK
2024-02-07 12:35:39,300 - INFO     - fhempy.lib.fhem_pythonbinding: Starting fhempy 0.1.718...
2024-02-07 12:35:39,321 - INFO     - fhempy.lib.fhem_pythonbinding: Waiting for FHEM connection
2024-02-07 12:35:39,792 - INFO     - websockets.server: server listening on 0.0.0.0:15733
2024-02-07 12:35:48,320 - INFO     - websockets.server: connection open
2024-02-07 12:35:48,338 - INFO     - fhempy.lib.fhem_pythonbinding: Incoming FHEM connection: 127.0.0.1
2024-02-07 12:35:53,478 - INFO     - Eq3bt1: Define: eq3bt 00:1A:22:1B:D3:05
2024-02-07 12:35:53,604 - DEBUG    - Eq3bt1: rfkill is not present
2024-02-07 12:36:52,343 - DEBUG    - Eq3bt1: start update_all
2024-02-07 12:36:52,350 - DEBUG    - Eq3bt1: Querying the device..
2024-02-07 12:36:54,387 - INFO     - Eq3bt1: Device found via adapter hci0
/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/fhempy/lib/core/bluetoothle.py:224: FutureWarning: BLEDevice.rssi is deprecated and will be removed in a future version of Bleak, use AdvertisementData.rssi instead
  self._dev_hash, "rssi", self._device.rssi, 1
2024-02-07 12:36:59,375 - DEBUG    - Eq3bt1: start_notify for d0e8434d-cd29-0996-af41-6c90f4e0eb2a
2024-02-07 12:36:59,577 - ERROR    - Eq3bt1: Failed to subscribe to notifications
Traceback (most recent call last):
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/fhempy/lib/core/bluetoothle.py", line 242, in connect_once
    await self._subscribe_notifies()
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/fhempy/lib/core/bluetoothle.py", line 275, in _subscribe_notifies
    await self._client.start_notify(
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/bleak/__init__.py", line 717, in start_notify
    await self._backend.start_notify(characteristic, wrapped_callback, **kwargs)
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/bleak/backends/bluezdbus/client.py", line 1003, in start_notify
    assert_reply(reply)
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/bleak/backends/bluezdbus/utils.py", line 22, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.NotPermitted] Not paired
2024-02-07 12:37:02,718 - DEBUG    - Eq3bt1: Querying id..
2024-02-07 12:37:05,822 - DEBUG    - Eq3bt1: Querying schedule..
2024-02-07 12:37:06,926 - DEBUG    - Eq3bt1: Querying schedule..`
etc.

connection has "connected (no notifications)"

I can control the device with the temperature slider, but I cannot get notifications (readings) so the connection seems right.  But why cannot I not get readings?  In case it is relevant my PIN is 6 digits and starts with a 0.  The unit displays it as 0XX then -XXX but I assume I remove the - to make it 0XXXXX and not 0XX-XXX.

**Comment by fhempy** [comment]
I just fixed the pairing mechanism. Which firmware version do you use on your thermostat? 120 or higher?

**Comment by fhempy** [comment]
👍 great!

Bluetoothctl consistently displays the output of any command executed across different bluetoothctl instances. Consequently, you can observe the results of fhempy commands issued to bluetoothctl within your own console.
