### ISSUE TITLE
Fhempy tuya smartlife integration

### ISSUE THREAD

**Issue by myModelY** [fhempy/fhempy#340]
Hi. With fhempy 0.718 it works fine. But with 0.720 not.
Module failed to load: tuya_smartlife
Maybe you need to update fhempy on this or remote peer.

Stacktrace:
Traceback (most recent call last):
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/fhempy/lib/fhem_pythonbinding.py", line 336, in handle_function
    module_object = await self.import_module(hash)
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/fhempy/lib/fhem_pythonbinding.py", line 573, in import_module
    module_object = await utils.run_blocking(
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/fhempy/lib/utils.py", line 72, in run_blocking
    return await asyncio.get_event_loop().run_in_executor(pool, function)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/fhempy/lib/tuya_smartlife/tuya_smartlife.py", line 5, in <module>
    import fhempy.lib.tuya_smartlife.tuya_smartlife_setup as tss
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/fhempy/lib/tuya_smartlife/tuya_smartlife_setup.py", line 6, in <module>
    from tuya_sharing import (
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/tuya_sharing/__init__.py", line 2, in <module>
    from .manager import Manager, SharingDeviceListener
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/tuya_sharing/manager.py", line 5, in <module>
    from .customerapi import CustomerApi, CustomerTokenInfo, SharingTokenListener
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/tuya_sharing/customerapi.py", line 12, in <module>
    from cryptography.hazmat.primitives.ciphers.aead import AESGCM
ModuleNotFoundError: No module named 'cryptography'

Module all installed

**Comment by fhempy** [comment]
It seems that the tuya-sharing-sdk library is missing the cryptography dependency. I added it to fhempy, please try again in a few minutes with the new fhempy release.

**Comment by myModelY** [comment]
thx a lot !

Am 16. Februar 2024 21:34:25 MEZ schrieb Dominik ***@***.***>:
>It seems that the tuya-sharing-sdk library is missing the cryptography dependency. I added it to fhempy, please try again in a few minutes with the new fhempy release.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/fhempy/fhempy/issues/340#issuecomment-1949295384
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
sent from K9-mail

**Comment by myModelY** [comment]
Hallo.
Folgende Fehlermeldung bei tuya_smartlife 

Failed to execute function Set: Traceback (most recent call last):
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.10/site-packages/fhempy/lib/fhem_pythonbinding.py", line 385, in handle_function
    ret = await self.execute_function(hash, fhem_reply_done, nmInstance)
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.10/site-packages/fhempy/lib/fhem_pythonbinding.py", line 484, in execute_function
    ret = await asyncio.wait_for(
  File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.10/site-packages/fhempy/lib/generic.py", line 208, in Set
    return await utils.handle_set(self._conf_set, self, hash, args, argsh)
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.10/site-packages/fhempy/lib/utils.py", line 340, in handle_set
    return await fct_call(hash, final_params)
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.10/site-packages/fhempy/lib/tuya_smartlife/tuya_smartlife.py", line 78, in set_colour_data
    await self.device.set_colour_data(hash, params)
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.10/site-packages/fhempy/lib/tuya_smartlife/tuya_smartlife_device.py", line 201, in set_colour_data
    if self._t_info["category"] == "dj":
TypeError: 'CustomerDevice' object is not subscriptable

**Comment by fhempy** [comment]
> Hallo. Folgende Fehlermeldung bei tuya_smartlife
> 
> Failed to execute function Set: Traceback (most recent call last): File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.10/site-packages/fhempy/lib/fhem_pythonbinding.py", line 385, in handle_function ret = await self.execute_function(hash, fhem_reply_done, nmInstance) File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.10/site-packages/fhempy/lib/fhem_pythonbinding.py", line 484, in execute_function ret = await asyncio.wait_for( File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for return fut.result() File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.10/site-packages/fhempy/lib/generic.py", line 208, in Set return await utils.handle_set(self._conf_set, self, hash, args, argsh) File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.10/site-packages/fhempy/lib/utils.py", line 340, in handle_set return await fct_call(hash, final_params) File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.10/site-packages/fhempy/lib/tuya_smartlife/tuya_smartlife.py", line 78, in set_colour_data await self.device.set_colour_data(hash, params) File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.10/site-packages/fhempy/lib/tuya_smartlife/tuya_smartlife_device.py", line 201, in set_colour_data if self._t_info["category"] == "dj": TypeError: 'CustomerDevice' object is not subscriptable

Besteht diese Fehlermeldung weiterhin bei dir?

**Comment by myModelY** [comment]
Hallo.
Mit letztem Update nicht mehr vorgekommen. 

Am 1. April 2024 10:38:28 MESZ schrieb Dominik ***@***.***>:
>> Hallo. Folgende Fehlermeldung bei tuya_smartlife
>> 
>> Failed to execute function Set: Traceback (most recent call last): File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.10/site-packages/fhempy/lib/fhem_pythonbinding.py", line 385, in handle_function ret = await self.execute_function(hash, fhem_reply_done, nmInstance) File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.10/site-packages/fhempy/lib/fhem_pythonbinding.py", line 484, in execute_function ret = await asyncio.wait_for( File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for return fut.result() File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.10/site-packages/fhempy/lib/generic.py", line 208, in Set return await utils.handle_set(self._conf_set, self, hash, args, argsh) File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.10/site-packages/fhempy/lib/utils.py", line 340, in handle_set return await fct_call(hash, final_params) File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.10/site-packages/fhempy/lib/tuya_smartlife/tuya_smartlife.py", line 78, in set_colour_data await self.device.set_colour_data(hash, params) File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.10/site-packages/fhempy/lib/tuya_smartlife/tuya_smartlife_device.py", line 201, in set_colour_data if self._t_info["category"] == "dj": TypeError: 'CustomerDevice' object is not subscriptable
>
>Besteht diese Fehlermeldung weiterhin bei dir?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/fhempy/fhempy/issues/340#issuecomment-2029411674
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
sent from K9-mail
