### ISSUE TITLE
fhempy merossintegration finds no devices

### ISSUE THREAD

**Issue by boeho01** [fhempy/fhempy#355]
Hello, I'm new here and have a problem with fhempy. I have reinstalled a FHEM server and fhempy works ok, but my devices are not found.
I have installed the following releases:
```
Ubuntu 10/23
perl 5.36.0
FHEM 6.3
```
fhempy seems to be working, as is the Meross integration.
```
fhempy_local connected 0.1.723
fhempyserver_15733 running
meross_integration connecting
```
But fhempy.log shows errors:
```
Activating virtual environment...OK
2024-02-22 13:09:39,871 - INFO - fhempy.lib.fhem_pythonbinding: Starting fhempy 0.1.723...
2024-02-22 13:09:39,871 - INFO - fhempy.lib.fhem_pythonbinding: Waiting for FHEM connection
2024-02-22 13:09:39,912 - INFO - websockets.server: server listening on 0.0.0.0:15733
2024-02-22 13:09:52,564 - INFO - websockets.server: connection open
2024-02-22 13:09:52,564 - INFO - fhempy.lib.fhem_pythonbinding: Incoming FHEM connection: 127.0.0.1
2024-02-22 13:09:54,287 - INFO - meross_iot.http_api: Login successful against https://iotx-eu.meross.com
Exception ignored in: <function Client.__del__ at 0x7f55b60ffc40>
Traceback (most recent call last):
   File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/paho/mqtt/client.py", line 874, in __del__
     self._reset_sockets()
   File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/paho/mqtt/client.py", line 1133, in _reset_sockets
     self._sock_close()
   File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/paho/mqtt/client.py", line 1119, in _sock_close
     if not self._sock:
            ^^^^^^^^^^
AttributeError: 'Client' object has no attribute '_sock'
2024-02-22 13:09:54,975 - ERROR - meross_integration: Exception raised by task: <Task finished name='Task-32' coro=<FhemModule._run_coro() done, defined at /opt/fhem/.fhempy/ fhempy_venv/lib/python3.11/site-packages/fhempy/lib/generic.py:216> exception=TypeError("Client.__init__() missing 1 required positional argument: 'callback_api_version'")>
Traceback (most recent call last):
   File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/generic.py", line 224, in _handle_task_result
     task.result()
   File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/generic.py", line 218, in _run_coro
     await coro
   File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/meross/meross_setup.py", line 39, in run_setup
     await manager.async_device_discovery()
   File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/meross_iot/manager.py", line 375, in async_device_discovery
     dev = await self._async_enroll_new_http_dev(d)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/meross_iot/manager.py", line 453, in _async_enroll_new_http_dev
     res_abilities = await self.async_execute_cmd(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/meross_iot/manager.py", line 846, in async_execute_cmd
     client = await self._async_get_create_mqtt_client(domain=mqtt_hostname, port=mqtt_port)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/meross_iot/manager.py", line 187, in _async_get_create_mqtt_client
     client = self._new_mqtt_client()
              ^^^^^^^^^^^^^^^^^^^^^^^
   File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/meross_iot/manager.py", line 209, in _new_mqtt_client
     client = mqtt.Client(client_id=self._client_id, protocol=mqtt.MQTTv311, clean_session=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Client.__init__() missing 1 required positional argument: 'callback_api_version'
```
I didn't see any errors during installation. Are the releases correct?
Regards boeho01

**Comment by fhempy** [comment]
Hi,
looks like an error in the meross-iot library. Can you please make sure that the username and password is correct? Is there anybody else who has the same issue?

**Comment by boeho01** [comment]
I repeated the steps for python3 (from others) and changed my pw without special chars.

Now I got 

`AttributeError: 'Client' object has no attribute '_sock'
2024-03-08 12:23:12,474 - ERROR    - meross_integration: Exception raised by task: <Task finished name='Task-65' coro=<FhemModule._run_coro() done, defined at /opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/generic.py:216> exception=TypeError("Client.__init__() missing 1 required positional argument: 'callback_api_version'")>
Traceback (most recent call last):
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/generic.py", line 224, in _handle_task_result
    task.result()
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/generic.py", line 218, in _run_coro
    await coro
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/meross/meross_setup.py", line 39, in run_setup
    await manager.async_device_discovery()
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/meross_iot/manager.py", line 375, in async_device_discovery
    dev = await self._async_enroll_new_http_dev(d)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/meross_iot/manager.py", line 453, in _async_enroll_new_http_dev
    res_abilities = await self.async_execute_cmd(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/meross_iot/manager.py", line 846, in async_execute_cmd
    client = await self._async_get_create_mqtt_client(domain=mqtt_hostname, port=mqtt_port)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/meross_iot/manager.py", line 187, in _async_get_create_mqtt_client
    client = self._new_mqtt_client()
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/meross_iot/manager.py", line 209, in _new_mqtt_client
    client = mqtt.Client(client_id=self._client_id, protocol=mqtt.MQTTv311, clean_session=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Client.__init__() missing 1 required positional argument: 'callback_api_version'
2024-03-08 12:24:20,566 - INFO     - fhempy.lib.fhem_pythonbinding: Start update...
2024-03-08 12:24:20,569 - INFO     - fhempy.lib.pkg_installer: Attempting install of fhempy
2024-03-08 12:25:14,581 - INFO     - fhempy.lib.pkg_installer: Successfully installed fhempy update!
2024-03-08 12:25:14,589 - INFO     - fhempy.lib.fhem_pythonbinding: Restart initiated...
2024-03-08 12:25:14,590 - INFO     - fhempy.lib.fhem_pythonbinding: All modules successfully undefined!
2024-03-08 12:25:14,590 - INFO     - websockets.server: server closing
2024-03-08 12:25:24,601 - INFO     - websockets.server: connection closed
2024-03-08 12:25:24,602 - INFO     - websockets.server: server closed
2024-03-08 12:25:24,610 - INFO     - fhempy.lib.fhem_pythonbinding: Exit 1
Activating virtual environment...OK
2024-03-08 12:25:25,778 - INFO     - fhempy.lib.fhem_pythonbinding: Starting fhempy 0.1.725...
2024-03-08 12:25:25,779 - INFO     - fhempy.lib.fhem_pythonbinding: Waiting for FHEM connection
2024-03-08 12:25:25,821 - INFO     - websockets.server: server listening on 0.0.0.0:15733
2024-03-08 12:25:34,662 - INFO     - websockets.server: connection open
2024-03-08 12:25:34,662 - INFO     - fhempy.lib.fhem_pythonbinding: Incoming FHEM connection: 127.0.0.1
2024-03-08 12:25:34,823 - INFO     - fhempy.lib.pkg_installer: Attempting install of meross-iot==0.4.6.2
2024-03-08 12:25:53,654 - INFO     - fhempy.lib.pkg_installer: Successfully installed meross-iot==0.4.6.2 update!
2024-03-08 12:25:57,445 - INFO     - meross_iot.http_api: Login successful against https://iotx-eu.meross.com
`

Because the first line in log was :AttributeError: 'Client' object has no attribute '_sock' I repeate
 `sudo cpan Protocol::WebSocket`
Result:
`Loading internal logger. Log::Log4perl recommended for better logging
Reading '/root/.cpan/Metadata'
  Database was generated on Fri, 08 Mar 2024 08:54:04 GMT
Protocol::WebSocket is up to date (0.26).
`

NOW fhempy is running and after 2 minutes was found all my devices !!
Dominik, it was a great job !!
Thanks Horst
