### ISSUE TITLE
fhempy in a crash loop on ZeroW

### ISSUE THREAD

**Issue by JorinL** [fhempy/fhempy#365]
Hey there,

got this problem now:

```
Mar 14 17:02:05 Zerow systemd[1]: Started fhempy.
Mar 14 17:02:11 Zerow fhempy[26432]: Traceback (most recent call last):
Mar 14 17:02:11 Zerow fhempy[26432]:   File "/home/pi/.fhempy/fhempy_venv/bin/fhempy", line 5, in <module>
Mar 14 17:02:11 Zerow fhempy[26432]:     from fhempy.lib.fhem_pythonbinding import run
Mar 14 17:02:11 Zerow fhempy[26432]:   File "/home/pi/.fhempy/fhempy_venv/lib/python3.9/site-packages/fhempy/lib/fhem_pythonbinding.py", line 18, in <module>
Mar 14 17:02:11 Zerow fhempy[26432]:     from .core.zeroconf import zeroconf
Mar 14 17:02:11 Zerow fhempy[26432]:   File "/home/pi/.fhempy/fhempy_venv/lib/python3.9/site-packages/fhempy/lib/core/zeroconf.py", line 4, in <module>
Mar 14 17:02:11 Zerow fhempy[26432]:     from zeroconf import Zeroconf
Mar 14 17:02:11 Zerow fhempy[26432]:   File "/home/pi/.fhempy/fhempy_venv/lib/python3.9/site-packages/zeroconf/__init__.py", line 25, in <module>
Mar 14 17:02:11 Zerow fhempy[26432]:     from ._cache import DNSCache  # noqa # import needed for backwards compat
Mar 14 17:02:11 Zerow fhempy[26432]:   File "src/zeroconf/_cache.py", line 1, in init zeroconf._cache
Mar 14 17:02:11 Zerow fhempy[26432]:   File "src/zeroconf/_protocol/incoming.py", line 1, in init zeroconf._protocol.incoming
Mar 14 17:02:11 Zerow fhempy[26432]:   File "src/zeroconf/_protocol/outgoing.py", line 1, in init zeroconf._protocol.outgoing
Mar 14 17:02:11 Zerow fhempy[26432]:   File "src/zeroconf/_dns.py", line 1, in init zeroconf._dns
Mar 14 17:02:11 Zerow fhempy[26432]: AttributeError: module 'zeroconf._utils.time' has no attribute '__pyx_capi__'
Mar 14 17:02:12 Zerow systemd[1]: fhempy.service: Main process exited, code=exited, status=1/FAILURE
Mar 14 17:02:12 Zerow systemd[1]: fhempy.service: Failed with result 'exit-code'.
Mar 14 17:02:12 Zerow systemd[1]: fhempy.service: Consumed 6.939s CPU time.
Mar 14 17:02:12 Zerow systemd[1]: fhempy.service: Scheduled restart job, restart counter is at 7.
Mar 14 17:02:12 Zerow systemd[1]: Stopped fhempy.

```

When installing the "long way":

 ```
........
 Using cached https://www.piwheels.org/simple/multidict/multidict-6.0.5-cp39-cp39-linux_armv6l.whl (118 kB)
Collecting attrs>=17.3.0
  Using cached https://www.piwheels.org/simple/attrs/attrs-23.2.0-py3-none-any.whl (60 kB)
Collecting aiosignal>=1.1.2
  Using cached https://www.piwheels.org/simple/aiosignal/aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting yarl<2.0,>=1.0
  Using cached https://www.piwheels.org/simple/yarl/yarl-1.9.4-cp39-cp39-linux_armv6l.whl (272 kB)
Collecting aiodns
  Using cached https://www.piwheels.org/simple/aiodns/aiodns-3.1.1-py3-none-any.whl (5.4 kB)
Collecting Brotli
  Using cached https://www.piwheels.org/simple/brotli/Brotli-1.1.0-cp39-cp39-linux_armv6l.whl (2.8 MB)
Collecting voluptuous>=0.12.1
  Using cached https://www.piwheels.org/simple/voluptuous/voluptuous-0.14.2-py3-none-any.whl (31 kB)
Collecting python-didl-lite~=1.4.0
  Using cached https://www.piwheels.org/simple/python-didl-lite/python_didl_lite-1.4.0-py3-none-any.whl (12 kB)
Collecting defusedxml>=0.6.0
  Using cached https://www.piwheels.org/simple/defusedxml/defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Collecting zipp>=0.5
  Using cached https://www.piwheels.org/simple/zipp/zipp-3.18.0-py3-none-any.whl (8.2 kB)
Collecting ptyprocess>=0.5
  Using cached https://www.piwheels.org/simple/ptyprocess/ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
Collecting charset-normalizer<4,>=2
  Using cached https://www.piwheels.org/simple/charset-normalizer/charset_normalizer-3.3.2-py3-none-any.whl (48 kB)
Collecting urllib3<3,>=1.21.1
  Using cached https://www.piwheels.org/simple/urllib3/urllib3-2.2.1-py3-none-any.whl (121 kB)
Collecting certifi>=2017.4.17
  Using cached https://www.piwheels.org/simple/certifi/certifi-2024.2.2-py3-none-any.whl (163 kB)
Collecting idna<4,>=2.5
  Using cached https://www.piwheels.org/simple/idna/idna-3.6-py3-none-any.whl (61 kB)
Collecting pycares>=4.0.0
  Using cached https://www.piwheels.org/simple/pycares/pycares-4.4.0-cp39-cp39-linux_armv6l.whl (242 kB)
Collecting cffi>=1.5.0
  Using cached https://www.piwheels.org/simple/cffi/cffi-1.16.0-cp39-cp39-linux_armv6l.whl (367 kB)
Collecting pycparser
  Using cached https://www.piwheels.org/simple/pycparser/pycparser-2.21-py2.py3-none-any.whl (119 kB)
Installing collected packages: pycparser, multidict, idna, frozenlist, cffi, yarl, pycares, defusedxml, attrs, async-timeout, aiosignal, zipp, voluptuous, urllib3, python-didl-lite, ptyprocess, ifaddr, charset-normalizer, certifi, Brotli, aiohttp, aiodns, zeroconf, websockets, requests, pycryptodomex, pexpect, packaging, markdown2, importlib-metadata, async-upnp-client, aiofiles, fhempy
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/var/log/.fhempy/fhempy_venv/lib/python3.9/site-packages/pycparser'
Consider using the `--user` option or check the permissions.
```

**Comment by fhempy** [comment]
I only found this article about that issue:
https://forums.indigodomo.com/viewtopic.php?t=27803&p=223311

You might try
```
source .fhempy/fhempy_venv/bin/activate
pip3 install --upgrade fhempy --nocache-dir
```

**Comment by JorinL** [comment]
Hey thanks for the help.

Tried it:

pi@Zerow:~ $ source .fhempy/fhempy_venv/bin/activate
(fhempy_venv) pi@Zerow:~ $ pip3 install --upgrade fhempy --nocache-dir
Usage:

```
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...
no such option: --nocache-dir
(fhempy_venv) pi@Zerow:~ $
```

**Comment by JorinL** [comment]
Ah seems '--no-cache-dir'

**Comment by JorinL** [comment]
Okay - I formatted the complete sd-card and reinstalled it all over again.

Now again running on the newest update.

Will see what happens on the next update :-D

Don't know what had happened here..... thanks for your support :-)
