### ISSUE TITLE
Tuya: Device erkannt / Bedienung nicht möglich 

### ISSUE THREAD

**Issue by DB1113** [fhempy/fhempy#431]
Hallo,

ich habe mir eine Pflanzenbewässerungspumpe beschafft.
Diese hat zwei separat ansteuerbare Pumpen (switch_1 & switch_2). Sie ist in Smart Life angelegt und lässt sich von dort steuern.

Ich habe den Local Key mit Tuya_system herausgefunden und das Device automatisch erstellen lassen.

In den Attributen im neuen Device "Pumpe" werden
dp_01 switch_1
dp_02 switch_2
dargestellt.

tuya_spec_functions
[{'code': 'switch_1', 'dp_id': 1, 'type': 'Boolean', 'values': "{}", 'desc': 'switch 1'}, {'code': 'switch_2', 'dp_id': 2, 'type': 'Boolean', 'values': "{}", 'desc': 'switch 2'}]

tuya_spec_status
[{"code": "switch_1", "dp_id": 1, "type": "Boolean", "values": "{}"}, {"code": "switch_2", "dp_id": 2, "type": "Boolean", "values": "{}"}]

In der Tuya-Cloud sind die Values noch mit "{true,false}" dargestellt. Allerdings hilft die Änderung mit diesen Values auch nicht bei dem folgenden Problem. Die Verwendung von " oder ' ist offensichtlich auch nicht ausschlaggebend. Alles mehrfach versucht.

Es tut sich nichts, wenn ich auf on klicke. 
Set Pumpe switch_1 on oder set Pumpe switch_2 on bewirkt auch nichts.

Habe ich etwas vergessen?

Danke für eine Rückmeldung.
MfG

EDIT:
Hab es mal mit tuya_smartlife versucht.
Pumpe 1 lässt sich so ansteuern. Bei Pumpe 2 kommt folgende Meldung:
`Failed to execute function Set: Traceback (most recent call last):
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/fhempy/lib/fhem_pythonbinding.py", line 385, in handle_function
    ret = await self.execute_function(hash, fhem_reply_done, nmInstance)
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/fhempy/lib/fhem_pythonbinding.py", line 484, in execute_function
    ret = await asyncio.wait_for(
  File "/usr/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/fhempy/lib/generic.py", line 208, in Set
    return await utils.handle_set(self._conf_set, self, hash, args, argsh)
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/fhempy/lib/utils.py", line 340, in handle_set
    return await fct_call(hash, final_params)
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/fhempy/lib/tuya_smartlife/tuya_smartlife.py", line 63, in set_boolean
    await self.device.set_boolean(hash, params)
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/fhempy/lib/tuya_smartlife/tuya_smartlife_device.py", line 170, in set_boolean
    code = params["function_param"]["code"]
TypeError: 'DeviceFunction' object is not subscriptable`

**Comment by DB1113** [comment]
Das Gerät war absoluter China-Schrott. Hat ständig die Verbindung zum WLan und/oder der Cloud verloren. Nicht brauchbar. Daher kann ich dazu jetzt auch nichts mehr weiter beitragen. Das Gerät ging zurück.
