### ISSUE TITLE
SkodaConnect - set_timer_schedule not working

### ISSUE THREAD

**Issue by jfmennedy** [fhempy/fhempy#473]
Hi, trying to set a timer schedule results in error:

`
Failed to execute function Set: Traceback (most recent call last):
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/fhem_pythonbinding.py", line 385, in handle_function
    ret = await self.execute_function(hash, fhem_reply_done, nmInstance)
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/fhem_pythonbinding.py", line 484, in execute_function
    ret = await asyncio.wait_for(
  File "/usr/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/generic.py", line 208, in Set
    return await utils.handle_set(self._conf_set, self, hash, args, argsh)
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/utils.py", line 339, in handle_set
    fct_call = getattr(obj, fct_name)
AttributeError: 'skodaconnect' object has no attribute 'set_timer_1_schedule'
`

Does it need some update due to changings in the base lib? 
The example.py is documented as this to set the schedule:
`
vehicle.set_timer_schedule(id = 1,
schedule = {
"enabled": True,
"recurring": True,
"date": "2021-05-21", 
"time": "08:00", 
"days": "nyynnnn",
"nightRateActive": True, 
"nightRateStart": "00:00", 
"nightRateEnd": "06:00",
"operationCharging": True, 
"operationClimatisation": True,
"targetTemp": 22, })
`

Greetings, Jan

**Comment by jfmennedy** [comment]
Hi,

I just encountered, there is a new library to implement skoda to fhempy.. It is a completely new project from the developpers of the old library... You can find this at https://myskoda.readthedocs.io/en/latest/

I tried to start with a new implementation, but i am allready stuck when just trying to install myskoda by manifest.json 

fhempy.lib.pkg_installer: Unable to install package myskoda: ERROR: Could not find a version that satisfies the requirement myskoda

myskoda is available at pipy and also at github... why fhempy does not find it?

Greatings Jan

PS. I will close this one and open a new issue for myskoda implementation
