### ISSUE TITLE
Fhempy traceback im container

### ISSUE THREAD

**Issue by sidey79** [fhempy/fhempy#94]
Ich habe angefangen einen docker Container für fhempy zu erzeugen. 
https://github.com/fhem/fhempy-docker

Installiert ist alles soweit ich sehen konnte richtig, aber beim starten von fhempy gibt es einen Fehler.

Perkussion denied ist mir aufgefallen, aber nähere Details finde ich keine.

Woran könnte das liegen?

```

2022-09-19 19:11:25,144 - ERROR    - __main__: Failed to load fhempy
Traceback (most recent call last):
  File "/usr/local/bin/fhempy", line 132, in <module>
    import fhempy.lib.fhem_pythonbinding as fpb
  File "/usr/local/lib/python3.9/site-packages/fhempy/lib/fhem_pythonbinding.py", line 16, in <module>
    from . import fhem, pkg_installer, utils, version
  File "/usr/local/lib/python3.9/site-packages/fhempy/lib/pkg_installer.py", line 20, in <module>
    pip_lock = asyncio.Lock()
  File "/usr/local/lib/python3.9/asyncio/locks.py", line 81, in __init__
    self._loop = events.get_event_loop()
  File "/usr/local/lib/python3.9/asyncio/events.py", line 639, in get_event_loop
    self.set_event_loop(self.new_event_loop())
  File "/usr/local/lib/python3.9/asyncio/events.py", line 659, in new_event_loop
    return self._loop_factory()
  File "/usr/local/lib/python3.9/asyncio/unix_events.py", line 54, in __init__
    super().__init__(selector)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 50, in __init__
    super().__init__()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 402, in __init__
    self._clock_resolution = time.get_clock_info('monotonic').resolution
PermissionError: [Errno 1] Operation not permitted
Exception ignored in: <function BaseEventLoop.__del__ at 0x76091898>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 686, in __del__
    _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 424, in __repr__
    f'closed={self.is_closed()} debug={self.get_debug()}>'
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1924, in get_debug
    return self._debug
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_debug'

      
      
```

**Comment by fhempy** [comment]
Hi,

ich habe das hier dazu gefunden:
https://github.com/synesthesiam/opentts/issues/11

Kannst du das bitte ausprobieren?

**Comment by sidey79** [comment]
Danke für diesen Tipp,

So startet der Container ohne Fehler :)

```
2022-09-20 06:59:50,269 - INFO     - fhempy.lib.fhem_pythonbinding: Starting fhempy 0.1.467...
2022-09-20 06:59:50,283 - INFO     - fhempy.lib.pkg_installer: Attempting install of async-upnp-client==0.31.2
2022-09-20 06:59:53,297 - INFO     - fhempy.lib.pkg_installer: Successfully installed async-upnp-client==0.31.2 update!
2022-09-20 06:59:53,298 - INFO     - fhempy.lib.fhem_pythonbinding: Advertise fhempy on local network
2022-09-20 06:59:53,655 - INFO     - fhempy.lib.fhem_pythonbinding: Waiting for FHEM connection
2022-09-20 06:59:53,669 - INFO     - websockets.server: server listening on 0.0.0.0:15733
```

**Comment by sidey79** [comment]
Ich habe jetzt herausgefunden, dass es ein Versionsabängiges Problem ist und nur Auftritt wenn der Host eine fehlende behaftete Version von linseeccomp eingesetzt wird.

https://github.com/freqtrade/freqtrade/issues/6183
