### ISSUE TITLE
Connection refused direkt nach Neuinstallation

### ISSUE THREAD

**Issue by ahermann86** [fhempy/fhempy#95]
Hallo,

Ich habe gestern einen orangepi mit Armbian Jammy (Ubuntu 22.04.1 LTS) frisch aufgesetzt. 
FHEM funktioniert und auf externe Schnittstellen (Uart...) kann zugegriffen werden. Zugriffsrechte sollten soweit passen.

Ich habe den Punkt 1 von [hier](https://forum.fhem.de/index.php/topic,127441.msg1219708.html#msg1219708) mit den Befehlen von "Debian 11 (Bullseye)" nach Anleitung durchgemacht. Es gab bei der Installation keine Fehler.

Als Letztes habe ich fhempy_local in FHEM definiert und habe gewartet... 

Das Ergebnis:

Der Punkt im Status bleibt rot und das Reading "prev_error" ist "127.0.0.1: Connection refused (111)"

Im Fhem-Log steht das drin:

2022.09.21 12:41:14 0: Featurelevel: 6.1
2022.09.21 12:41:14 0: Server started with 55 defined entities (fhem.pl:26379/2022-09-03 perl:5.034000 os:linux user:fhem pid:2091)
2022.09.21 12:41:19 1: fhempy_local: Can't connect to ws:127.0.0.1:15733: Operation now in progress
2022.09.21 12:41:19 1: fhempy_local: Can't connect to ws:127.0.0.1:15733: 127.0.0.1: Connection refused (111)
2022.09.21 12:41:19 1: BindingsIo (fhempy_local): ERROR during connection setup: 127.0.0.1: Connection refused (111)

Was mache ich falsch?

Gruß Axel

**Comment by fhempy** [comment]
Hi,
was steht im fhempy Log? Wie lange hast dunnach dem define gewartet? Dauert nämlich ca. 15min bis alles installiert ist.

**Comment by ahermann86** [comment]
Jetzt habe ich erst gesehen. Es gibt ein fhempy-2022-09-21.log:

[fhempy-2022-09-21.log](https://github.com/fhempy/fhempy/files/9619420/fhempy-2022-09-21.log)

..so wie ich das sehe, fehlt da irgendwas..?

-------------------------

note: This error originates from a subprocess, and is likely not a problem with pip.
2022-09-21 20:19:50,352 - ERROR    - __main__: Failed to install fhempy, exit now...
2022-09-21 20:20:50,846 - ERROR    - __main__: Failed to load fhempy
Traceback (most recent call last):
  File "/opt/fhem/FHEM/bindings/python/bin/fhempy", line 132, in <module>
    import fhempy.lib.fhem_pythonbinding as fpb
ModuleNotFoundError: No module named 'fhempy'
2022-09-21 20:20:50,849 - INFO     - __main__: Attempting install of fhempy>=0.1.462
2022-09-21 20:22:50,566 - ERROR    - __main__: Unable to install package fhempy>=0.1.462: error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      
              =============================DEBUG ASSISTANCE==========================
              If you are seeing an error here please try the following to
              successfully install cryptography:
      
              Upgrade to the latest pip and try again. This will fix errors for most
              users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
              =============================DEBUG ASSISTANCE==========================
      
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 14, in <module>
          from setuptools_rust import RustExtension
        File "/tmp/pip-build-env-a17pgzfe/overlay/local/lib/python3.10/dist-packages/setuptools_rust/__init__.py", line 1, in <module>
          from .build import build_rust
        File "/tmp/pip-build-env-a17pgzfe/overlay/local/lib/python3.10/dist-packages/setuptools_rust/build.py", line 23, in <module>
          from setuptools.command.build import build as CommandBuild  # type: ignore[import]
      ModuleNotFoundError: No module named 'setuptools.command.build'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
2022-09-21 20:22:50,567 - ERROR    - __main__: Failed to install fhempy, exit now...
2022-09-21 20:23:51,029 - ERROR    - __main__: Failed to load fhempy
Traceback (most recent call last):
  File "/opt/fhem/FHEM/bindings/python/bin/fhempy", line 132, in <module>
    import fhempy.lib.fhem_pythonbinding as fpb
ModuleNotFoundError: No module named 'fhempy'
2022-09-21 20:23:51,032 - INFO     - __main__: Attempting install of fhempy>=0.1.462

**Comment by fhempy** [comment]
Versuch mal
```
sudo apt-get install python3-setuptools
```

**Comment by fhempy** [comment]
Ich dachte mir das hatten wir schon mal...das ist hier noch offen:
https://github.com/fhempy/fhempy/issues/85#issuecomment-1221599571

Bitte in dem anderen Issue weiter antworten. Ich hatte mit kleinerDrache vereinbart, dass ich mich mal auf seinen Rechner connecte, leider sind wir noch nicht dazu gekommen.
